// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: yingyuan

#include "../ui.h"

void ui_dingdan_screen_init(void)
{
    ui_dingdan = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dingdan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dindanxinxi = lv_obj_create(ui_dingdan);
    lv_obj_remove_style_all(ui_dindanxinxi);
    lv_obj_set_width(ui_dindanxinxi, 538);
    lv_obj_set_height(ui_dindanxinxi, 37);
    lv_obj_set_x(ui_dindanxinxi, -127);
    lv_obj_set_y(ui_dindanxinxi, 217);
    lv_obj_set_align(ui_dindanxinxi, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_dindanxinxi, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_dindanxinxi, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_dindanxinxi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_dindanxinxi, lv_color_hex(0x666060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dindanxinxi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_dindanxinxi, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_dindanxinxi, lv_color_hex(0x544C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_dindanxinxi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label85 = lv_label_create(ui_dindanxinxi);
    lv_obj_set_width(ui_Label85, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label85, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label85, LV_ALIGN_CENTER);
    date1(ui_Label85);
    lv_obj_set_style_text_color(ui_Label85, lv_color_hex(0x0A0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label85, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label85, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label80 = lv_label_create(ui_dindanxinxi);
    lv_obj_set_width(ui_Label80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label80, 15);
    lv_obj_set_y(ui_Label80, -1);
    lv_obj_set_align(ui_Label80, LV_ALIGN_CENTER);
    week1(ui_Label80);
    lv_obj_set_style_text_color(ui_Label80, lv_color_hex(0x00FF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label80, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label82 = lv_label_create(ui_dindanxinxi);
    lv_obj_set_width(ui_Label82, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label82, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label82, 37);
    lv_obj_set_y(ui_Label82, -1);
    lv_obj_set_align(ui_Label82, LV_ALIGN_CENTER);
    weather1(ui_Label82);
    lv_obj_set_style_text_color(ui_Label82, lv_color_hex(0xF000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label82, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label82, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label83 = lv_label_create(ui_dindanxinxi);
    lv_obj_set_width(ui_Label83, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label83, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label83, 22);
    lv_obj_set_y(ui_Label83, 0);
    lv_obj_set_align(ui_Label83, LV_ALIGN_CENTER);
    clock1(ui_Label83);
    lv_obj_set_style_text_color(ui_Label83, lv_color_hex(0x00DBFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label83, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label83, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_orderlist1 = lv_obj_create(ui_dingdan);
    lv_obj_remove_style_all(ui_orderlist1);

    ui_orderlist1 = lv_obj_create(ui_dingdan);
    lv_obj_remove_style_all(ui_orderlist1);

    lv_obj_set_width(ui_orderlist1, 800);                 // ★ 补回宽度（屏幕宽）
    lv_obj_set_height(ui_orderlist1, LV_VER_RES - 45);
    lv_obj_set_align(ui_orderlist1, LV_ALIGN_TOP_MID);    // ★ 只留这一行对齐，删掉下面的 CENTER


    lv_obj_set_flex_flow(ui_orderlist1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_orderlist1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    
    lv_obj_clear_flag(ui_orderlist1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);   /* 裁剪超界卡片，不盖底栏 */
    lv_obj_clear_flag(ui_orderlist1, LV_OBJ_FLAG_SCROLL_ELASTIC);     /* 关掉橡皮筋回弹 */

    // lv_obj_clear_flag(ui_orderlist1, LV_OBJ_FLAG_CLICKABLE);      /// Flags


    lv_obj_set_scrollbar_mode(ui_orderlist1, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_orderlist1, LV_DIR_VER);

  
    lv_obj_set_style_width(ui_orderlist1, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);      // 滚动条宽5px
    lv_obj_set_style_radius(ui_orderlist1, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_orderlist1, lv_color_hex(0x888888), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_orderlist1, LV_OPA_70, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
  

   
    lv_obj_set_style_pad_left(ui_orderlist1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_orderlist1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_orderlist1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_orderlist1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_orderlist1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_orderlist1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_orderlist1, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_orderlist1, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_orderlist1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_orderlist1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_orderlist1, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_orderlist1, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_template = lv_obj_create(ui_orderlist1);
    lv_obj_remove_style_all(ui_template);
    lv_obj_set_height(ui_template, 130);
    lv_obj_set_width(ui_template, 800);

    lv_obj_set_align(ui_template, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_template, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_template, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_template, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_template, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_template, lv_color_hex(0xBE9090), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_template, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_template, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_template, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_template, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_template, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_template, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_template, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_template, 8, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_template, lv_color_hex(0xB9A5A5), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_template, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_template, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_template, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_template, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_template, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_template, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_template, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_rowticket = lv_obj_create(ui_template);
    lv_obj_remove_style_all(ui_rowticket);
    lv_obj_set_height(ui_rowticket, 60);
    lv_obj_set_width(ui_rowticket, lv_pct(100));
    lv_obj_set_align(ui_rowticket, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rowticket, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_rowticket, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_rowticket, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_left = lv_obj_create(ui_rowticket);
    lv_obj_remove_style_all(ui_left);
    lv_obj_set_height(ui_left, lv_pct(100));
    lv_obj_set_flex_grow(ui_left, 1);
    lv_obj_set_align(ui_left, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_left, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_left, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_left, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelmovie = lv_label_create(ui_left);
    lv_obj_set_width(ui_Labelmovie, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelmovie, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelmovie, 5);
    lv_obj_set_y(ui_Labelmovie, 0);
    lv_obj_set_align(ui_Labelmovie, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelmovie, "电影名:GGBOND");
    lv_obj_set_style_text_color(ui_Labelmovie, lv_color_hex(0x140202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelmovie, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelmovie, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelsession = lv_label_create(ui_left);
    lv_obj_set_width(ui_Labelsession, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelsession, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelsession, 1);
    lv_obj_set_y(ui_Labelsession, 92);
    lv_obj_set_align(ui_Labelsession, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelsession, "09-12 14:30  - 5号厅 -  7排5座");
    lv_obj_set_style_text_color(ui_Labelsession, lv_color_hex(0x472A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelsession, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelsession, &ui_font_zzzz30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelprice = lv_label_create(ui_rowticket);
    lv_obj_set_width(ui_Labelprice, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelprice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelprice, -1);
    lv_obj_set_y(ui_Labelprice, 21);
    lv_obj_set_align(ui_Labelprice, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelprice, "￥200.00");
    lv_obj_set_style_text_color(ui_Labelprice, lv_color_hex(0xFFD100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelprice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelprice, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_divider = lv_obj_create(ui_template);
    lv_obj_remove_style_all(ui_divider);
    lv_obj_set_height(ui_divider, 2);
    lv_obj_set_width(ui_divider, lv_pct(100));
    lv_obj_set_x(ui_divider, -4);
    lv_obj_set_y(ui_divider, 3);
    lv_obj_set_align(ui_divider, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_divider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_divider, lv_color_hex(0x0F0707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_divider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rowsnacks = lv_obj_create(ui_template);
    lv_obj_remove_style_all(ui_rowsnacks);
    lv_obj_set_height(ui_rowsnacks, 30);
    lv_obj_set_width(ui_rowsnacks, lv_pct(100));
    lv_obj_set_align(ui_rowsnacks, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rowsnacks, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_rowsnacks, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_rowsnacks, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labeleattitle = lv_label_create(ui_rowsnacks);
    lv_obj_set_width(ui_Labeleattitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeleattitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labeleattitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeleattitle, "小吃：");
    lv_obj_set_style_text_font(ui_Labeleattitle, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label86 = lv_label_create(ui_rowsnacks);
    lv_obj_set_width(ui_Label86, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label86, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label86, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label86, "冰红茶 * 1  薯条 *2");
    lv_obj_set_style_text_font(ui_Label86, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

}
