// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: yingyuan

#include "../ui.h"

void ui_food_screen_init(void)
{
    ui_food = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_food, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel11 = lv_obj_create(ui_food);
    lv_obj_set_width(ui_Panel11, 800);
    lv_obj_set_height(ui_Panel11, 60);
    lv_obj_set_x(ui_Panel11, -7);
    lv_obj_set_y(ui_Panel11, -212);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xBEBCBC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_total2 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_total2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_total2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_total2, -75);
    lv_obj_set_y(ui_total2, 1);
    lv_obj_set_align(ui_total2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_total2, "总计： 0元");
    lv_obj_set_style_text_font(ui_total2, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number2 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_number2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_number2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_number2, -321);
    lv_obj_set_y(ui_number2, 1);
    lv_obj_set_align(ui_number2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number2, "已选:0 个");
    lv_obj_set_style_text_font(ui_number2, &ui_font_zzzz30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_Panel11);
    lv_obj_set_width(ui_Button10, 100);
    lv_obj_set_height(ui_Button10, 50);
    lv_obj_set_x(ui_Button10, 304);
    lv_obj_set_y(ui_Button10, 2);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xFF0035), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 1);
    lv_obj_set_y(ui_Label27, 0);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "去支付");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x160303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_food);
    lv_obj_set_width(ui_Panel10, 790);
    lv_obj_set_height(ui_Panel10, 395);
    lv_obj_set_x(ui_Panel10, -3);
    lv_obj_set_y(ui_Panel10, 15);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Panel10, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Panel10, LV_DIR_VER);

    ui_ImgButton15 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_ImgButton15, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ls_png, NULL);
 
    lv_obj_set_width(ui_ImgButton15, 300);
    lv_obj_set_height(ui_ImgButton15, 200);
    lv_obj_set_x(ui_ImgButton15, 170);
    lv_obj_set_y(ui_ImgButton15, 156);
    lv_obj_set_align(ui_ImgButton15, LV_ALIGN_CENTER);

    ui_ImgButton16 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_ImgButton16, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_zxf_png, NULL);
 
    lv_obj_set_width(ui_ImgButton16, 300);
    lv_obj_set_height(ui_ImgButton16, 200);
    lv_obj_set_x(ui_ImgButton16, -243);
    lv_obj_set_y(ui_ImgButton16, 152);
    lv_obj_set_align(ui_ImgButton16, LV_ALIGN_CENTER);

    ui_ImgButton18 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_ImgButton18, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_mx_png, NULL);

    lv_obj_set_width(ui_ImgButton18, 300);
    lv_obj_set_height(ui_ImgButton18, 200);
    lv_obj_set_x(ui_ImgButton18, 165);
    lv_obj_set_y(ui_ImgButton18, -105);
    lv_obj_set_align(ui_ImgButton18, LV_ALIGN_CENTER);

    ui_ImgButton17 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_ImgButton17, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_man_png, NULL);
 
    lv_obj_set_width(ui_ImgButton17, 300);
    lv_obj_set_height(ui_ImgButton17, 200);
    lv_obj_set_x(ui_ImgButton17, -247);
    lv_obj_set_y(ui_ImgButton17, -113);
    lv_obj_set_align(ui_ImgButton17, LV_ALIGN_CENTER);

    ui_ImgButton19 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_ImgButton19, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1081085947, NULL);
    
    lv_obj_set_width(ui_ImgButton19, 300);
    lv_obj_set_height(ui_ImgButton19, 200);
    lv_obj_set_x(ui_ImgButton19, -242);
    lv_obj_set_y(ui_ImgButton19, 449);
    lv_obj_set_align(ui_ImgButton19, LV_ALIGN_CENTER);

    ui_ImgButton20 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_ImgButton20, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_kfc_png, NULL);
  
    lv_obj_set_width(ui_ImgButton20, 300);
    lv_obj_set_height(ui_ImgButton20, 200);
    lv_obj_set_x(ui_ImgButton20, 186);
    lv_obj_set_y(ui_ImgButton20, 432);
    lv_obj_set_align(ui_ImgButton20, LV_ALIGN_CENTER);

    ui_Label25 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -35);
    lv_obj_set_y(ui_Label25, -84);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "冰\n红\n茶\n\n4\n元");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 345);
    lv_obj_set_y(ui_Label28, -90);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "劲\n凉\n\n5\n元");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -41);
    lv_obj_set_y(ui_Label29, 114);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "雷\n碧\n\n4\n元");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 355);
    lv_obj_set_y(ui_Label30, 130);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "美\n年\n达\n\n5\n元");
    lv_obj_set_style_text_font(ui_Label30, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -39);
    lv_obj_set_y(ui_Label31, 432);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "薯\n条\n\n20\n元");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 370);
    lv_obj_set_y(ui_Label32, 437);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "肯\n德\n基\n\n50\n元");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jian1 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_jian1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1482295748, NULL);

    lv_obj_set_height(ui_jian1, 64);
    lv_obj_set_width(ui_jian1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_jian1, -302);
    lv_obj_set_y(ui_jian1, 30);
    lv_obj_set_align(ui_jian1, LV_ALIGN_CENTER);

    ui_add1 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_add1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1735873665, NULL);
   
    lv_obj_set_height(ui_add1, 64);
    lv_obj_set_width(ui_add1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_add1, -162);
    lv_obj_set_y(ui_add1, 29);
    lv_obj_set_align(ui_add1, LV_ALIGN_CENTER);

    ui_jian3 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_jian3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1482295748, NULL);

    lv_obj_set_height(ui_jian3, 64);
    lv_obj_set_width(ui_jian3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_jian3, -303);
    lv_obj_set_y(ui_jian3, 286);
    lv_obj_set_align(ui_jian3, LV_ALIGN_CENTER);

    ui_jian4 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_jian4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1482295748, NULL);

    lv_obj_set_height(ui_jian4, 64);
    lv_obj_set_width(ui_jian4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_jian4, 125);
    lv_obj_set_y(ui_jian4, 288);
    lv_obj_set_align(ui_jian4, LV_ALIGN_CENTER);

    ui_jian5 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_jian5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1482295748, NULL);

    lv_obj_set_height(ui_jian5, 64);
    lv_obj_set_width(ui_jian5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_jian5, -282);
    lv_obj_set_y(ui_jian5, 588);
    lv_obj_set_align(ui_jian5, LV_ALIGN_CENTER);

    ui_jian6 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_jian6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1482295748, NULL);
  
    lv_obj_set_height(ui_jian6, 64);
    lv_obj_set_width(ui_jian6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_jian6, 143);
    lv_obj_set_y(ui_jian6, 586);
    lv_obj_set_align(ui_jian6, LV_ALIGN_CENTER);

    ui_jian2 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_jian2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1482295748, NULL);
 
    lv_obj_set_height(ui_jian2, 64);
    lv_obj_set_width(ui_jian2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_jian2, 116);
    lv_obj_set_y(ui_jian2, 32);
    lv_obj_set_align(ui_jian2, LV_ALIGN_CENTER);

    ui_add3 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_add3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1735873665, NULL);
   
    lv_obj_set_height(ui_add3, 64);
    lv_obj_set_width(ui_add3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_add3, -168);
    lv_obj_set_y(ui_add3, 288);
    lv_obj_set_align(ui_add3, LV_ALIGN_CENTER);

    ui_add4 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_add4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1735873665, NULL);
  
    lv_obj_set_height(ui_add4, 64);
    lv_obj_set_width(ui_add4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_add4, 248);
    lv_obj_set_y(ui_add4, 285);
    lv_obj_set_align(ui_add4, LV_ALIGN_CENTER);

    ui_add5 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_add5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1735873665, NULL);
   
    lv_obj_set_height(ui_add5, 64);
    lv_obj_set_width(ui_add5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_add5, -133);
    lv_obj_set_y(ui_add5, 584);
    lv_obj_set_align(ui_add5, LV_ALIGN_CENTER);

    ui_add6 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_add6, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1735873665, NULL);
   
    lv_obj_set_height(ui_add6, 64);
    lv_obj_set_width(ui_add6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_add6, 291);
    lv_obj_set_y(ui_add6, 580);
    lv_obj_set_align(ui_add6, LV_ALIGN_CENTER);

    ui_add2 = lv_imgbtn_create(ui_Panel10);
    lv_imgbtn_set_src(ui_add2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1735873665, NULL);
   
    lv_obj_set_width(ui_add2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_add2, 234);
    lv_obj_set_y(ui_add2, 30);
    lv_obj_set_align(ui_add2, LV_ALIGN_CENTER);

    ui_Container10 = lv_obj_create(ui_food);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 538);
    lv_obj_set_height(ui_Container10, 25);
    lv_obj_set_x(ui_Container10, -128);
    lv_obj_set_y(ui_Container10, 225);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container10, lv_color_hex(0x666060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container10, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container10, lv_color_hex(0x544C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label66 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label66, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label66, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label66, LV_ALIGN_CENTER);
    date1(ui_Label66);
    lv_obj_set_style_text_color(ui_Label66, lv_color_hex(0x0F0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label66, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label66, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label67 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label67, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label67, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label67, 15);
    lv_obj_set_y(ui_Label67, -1);
    lv_obj_set_align(ui_Label67, LV_ALIGN_CENTER);
    week1(ui_Label67);
    lv_obj_set_style_text_color(ui_Label67, lv_color_hex(0x00FF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label67, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label67, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label68 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label68, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label68, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label68, 37);
    lv_obj_set_y(ui_Label68, -1);
    lv_obj_set_align(ui_Label68, LV_ALIGN_CENTER);
    weather1(ui_Label68);
    lv_obj_set_style_text_color(ui_Label68, lv_color_hex(0xFEF600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label68, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label68, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label69 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label69, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label69, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label69, 22);
    lv_obj_set_y(ui_Label69, 0);
    lv_obj_set_align(ui_Label69, LV_ALIGN_CENTER);
    clock1(ui_Label69);
    lv_obj_set_style_text_color(ui_Label69, lv_color_hex(0x00DBFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label69, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label69, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_jian1, ui_event_jian1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_add1, ui_event_add1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_jian3, ui_event_jian3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_jian4, ui_event_jian4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_jian5, ui_event_jian5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_jian6, ui_event_jian6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_jian2, ui_event_jian2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_add3, ui_event_add3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_add4, ui_event_add4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_add5, ui_event_add5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_add6, ui_event_add6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_add2, ui_event_add2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_food, ui_event_food, LV_EVENT_ALL, NULL);

}
