// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: loginUI

#include "../ui.h"

void ui_failed_screen_init(void)
{
    ui_failed = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_failed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_failed);
    lv_img_set_src(ui_Image2, &ui_img_failed_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image2, 5);


    ui_Label16 = lv_label_create(ui_failed);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 3);
    lv_obj_set_y(ui_Label16, -183);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "ERROR!!!!!");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

}
