// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: yingyuan

#include "../ui.h"

void ui_guangao_screen_init(void)
{
    ui_guangao = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_guangao, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_guangao, &ui_img_yyy_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imgbtn_create(ui_guangao);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_623033322, NULL);

    lv_obj_set_height(ui_ImgButton1, 80);
    lv_obj_set_width(ui_ImgButton1, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_x(ui_ImgButton1, 314);
    lv_obj_set_y(ui_ImgButton1, -155);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    ui_Container3 = lv_obj_create(ui_guangao);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 538);
    lv_obj_set_height(ui_Container3, 25);
    lv_obj_set_x(ui_Container3, 124);
    lv_obj_set_y(ui_Container3, 223);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0x666060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container3, lv_color_hex(0x544C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    date1(ui_Label41);
    lv_obj_set_style_text_color(ui_Label41, lv_color_hex(0x0B0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label41, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 15);
    lv_obj_set_y(ui_Label37, -1);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    week1(ui_Label37);
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0x00FF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 37);
    lv_obj_set_y(ui_Label38, -1);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    weather1(ui_Label38);
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0xFEF600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 22);
    lv_obj_set_y(ui_Label39, 0);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    clock1(ui_Label39);
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0x00DBFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);

}
