// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: yingyuan

#include "../ui.h"

void ui_movie_screen_init(void)
{
    ui_movie = lv_obj_create(NULL);
    lv_obj_add_flag(ui_movie, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_clear_flag(ui_movie, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_movie, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_movie, LV_DIR_VER);
    lv_obj_set_style_bg_grad_color(ui_movie, lv_color_hex(0xE5C2C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_movie, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panellan = lv_obj_create(ui_movie);
    lv_obj_set_width(ui_Panellan, 775);
    lv_obj_set_height(ui_Panellan, 58);
    lv_obj_set_x(ui_Panellan, 5);
    lv_obj_set_y(ui_Panellan, -215);
    lv_obj_set_align(ui_Panellan, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panellan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_Panellan);
    lv_obj_set_width(ui_Button4, 196);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 263);
    lv_obj_set_y(ui_Button4, 3);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x0F0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelcowmine = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Labelcowmine, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelcowmine, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labelcowmine, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelcowmine, "我的");
    lv_obj_set_style_text_font(ui_Labelcowmine, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonyinyuan = lv_btn_create(ui_Panellan);
    lv_obj_set_width(ui_Buttonyinyuan, 177);
    lv_obj_set_height(ui_Buttonyinyuan, 50);
    lv_obj_set_x(ui_Buttonyinyuan, -7);
    lv_obj_set_y(ui_Buttonyinyuan, 2);
    lv_obj_set_align(ui_Buttonyinyuan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonyinyuan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonyinyuan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonyinyuan, lv_color_hex(0x100C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonyinyuan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelyinyuan_ = lv_label_create(ui_Buttonyinyuan);
    lv_obj_set_width(ui_Labelyinyuan_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelyinyuan_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelyinyuan_, -5);
    lv_obj_set_y(ui_Labelyinyuan_, -1);
    lv_obj_set_align(ui_Labelyinyuan_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelyinyuan_, "影院");
    lv_obj_set_style_text_font(ui_Labelyinyuan_, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buttonmovie = lv_btn_create(ui_Panellan);
    lv_obj_set_width(ui_Buttonmovie, 178);
    lv_obj_set_height(ui_Buttonmovie, 50);
    lv_obj_set_x(ui_Buttonmovie, -269);
    lv_obj_set_y(ui_Buttonmovie, 0);
    lv_obj_set_align(ui_Buttonmovie, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buttonmovie, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buttonmovie, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buttonmovie, lv_color_hex(0x0E0A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buttonmovie, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelmovie1 = lv_label_create(ui_Buttonmovie);
    lv_obj_set_width(ui_Labelmovie1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelmovie1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labelmovie1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelmovie1, "电影");
    lv_obj_set_style_text_color(ui_Labelmovie1, lv_color_hex(0xEBE1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelmovie1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelmovie1, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelmianban = lv_obj_create(ui_movie);
    lv_obj_set_width(ui_Panelmianban, 800);
    lv_obj_set_height(ui_Panelmianban, 400);
    lv_obj_set_x(ui_Panelmianban, 3);
    lv_obj_set_y(ui_Panelmianban, 22);
    lv_obj_set_align(ui_Panelmianban, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panelmianban, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_clear_flag(ui_Panelmianban, LV_OBJ_FLAG_PRESS_LOCK);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Panelmianban, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Panelmianban, LV_DIR_VER);

    lv_obj_set_style_bg_grad_color(ui_Panelmianban, lv_color_hex(0xEEA9A9), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panelmianban, LV_GRAD_DIR_VER, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panelhotmovie = lv_obj_create(ui_Panelmianban);
    lv_obj_set_width(ui_Panelhotmovie, 763);
    lv_obj_set_height(ui_Panelhotmovie, 160);
    lv_obj_set_x(ui_Panelhotmovie, -4);
    lv_obj_set_y(ui_Panelhotmovie, -75);
    lv_obj_set_align(ui_Panelhotmovie, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panelhotmovie, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Panelhotmovie, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Panelhotmovie, LV_DIR_HOR);

    ui_ImgButtonpig = lv_imgbtn_create(ui_Panelhotmovie);
    lv_imgbtn_set_src(ui_ImgButtonpig, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_pepepig_png, NULL);
  
    lv_obj_set_width(ui_ImgButtonpig, 200);
    lv_obj_set_height(ui_ImgButtonpig, 130);
    lv_obj_set_x(ui_ImgButtonpig, 518);
    lv_obj_set_y(ui_ImgButtonpig, -15);
    lv_obj_set_align(ui_ImgButtonpig, LV_ALIGN_CENTER);

    ui_ImgButtoncow = lv_imgbtn_create(ui_Panelhotmovie);
    lv_imgbtn_set_src(ui_ImgButtoncow, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_841450715, NULL);

    lv_obj_set_width(ui_ImgButtoncow, 200);
    lv_obj_set_height(ui_ImgButtoncow, 130);
    lv_obj_set_x(ui_ImgButtoncow, -275);
    lv_obj_set_y(ui_ImgButtoncow, -17);
    lv_obj_set_align(ui_ImgButtoncow, LV_ALIGN_CENTER);

    ui_Labelcow = lv_label_create(ui_Panelhotmovie);
    lv_obj_set_width(ui_Labelcow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelcow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelcow, -277);
    lv_obj_set_y(ui_Labelcow, 62);
    lv_obj_set_align(ui_Labelcow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelcow, "牛来");
    lv_obj_set_style_text_font(ui_Labelcow, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtondog = lv_imgbtn_create(ui_Panelhotmovie);
    lv_imgbtn_set_src(ui_ImgButtondog, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_620000976, NULL);

    lv_obj_set_width(ui_ImgButtondog, 200);
    lv_obj_set_height(ui_ImgButtondog, 130);
    lv_obj_set_x(ui_ImgButtondog, -11);
    lv_obj_set_y(ui_ImgButtondog, -14);
    lv_obj_set_align(ui_ImgButtondog, LV_ALIGN_CENTER);

    ui_Labeldog = lv_label_create(ui_Panelhotmovie);
    lv_obj_set_width(ui_Labeldog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeldog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeldog, -24);
    lv_obj_set_y(ui_Labeldog, 62);
    lv_obj_set_align(ui_Labeldog, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeldog, "汪汪队");
    lv_obj_set_style_text_font(ui_Labeldog, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButtonggbond = lv_imgbtn_create(ui_Panelhotmovie);
    lv_imgbtn_set_src(ui_ImgButtonggbond, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_ggbond_png, NULL);

    lv_obj_set_width(ui_ImgButtonggbond, 200);
    lv_obj_set_height(ui_ImgButtonggbond, 130);
    lv_obj_set_x(ui_ImgButtonggbond, 239);
    lv_obj_set_y(ui_ImgButtonggbond, -18);
    lv_obj_set_align(ui_ImgButtonggbond, LV_ALIGN_CENTER);

    ui_Labelggbond = lv_label_create(ui_Panelhotmovie);
    lv_obj_set_width(ui_Labelggbond, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelggbond, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelggbond, 241);
    lv_obj_set_y(ui_Labelggbond, 60);
    lv_obj_set_align(ui_Labelggbond, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelggbond, "GGBOND");
    lv_obj_set_style_text_font(ui_Labelggbond, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelpig = lv_label_create(ui_Panelhotmovie);
    lv_obj_set_width(ui_Labelpig, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelpig, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelpig, 520);
    lv_obj_set_y(ui_Labelpig, 63);
    lv_obj_set_align(ui_Labelpig, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelpig, "小猪佩奇");
    lv_obj_set_style_text_font(ui_Labelpig, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panellastmovie = lv_obj_create(ui_Panelmianban);
    lv_obj_set_width(ui_Panellastmovie, 763);
    lv_obj_set_height(ui_Panellastmovie, 160);
    lv_obj_set_x(ui_Panellastmovie, 1);
    lv_obj_set_y(ui_Panellastmovie, 115);
    lv_obj_set_align(ui_Panellastmovie, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panellastmovie, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Panellastmovie, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Panellastmovie, LV_DIR_HOR);

    ui_ImgButtonlong4 = lv_imgbtn_create(ui_Panellastmovie);
    lv_imgbtn_set_src(ui_ImgButtonlong4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_663409996, NULL);

    lv_obj_set_width(ui_ImgButtonlong4, 200);
    lv_obj_set_height(ui_ImgButtonlong4, 130);
    lv_obj_set_x(ui_ImgButtonlong4, 515);
    lv_obj_set_y(ui_ImgButtonlong4, -24);
    lv_obj_set_align(ui_ImgButtonlong4, LV_ALIGN_CENTER);

    ui_ImgButtonlong3 = lv_imgbtn_create(ui_Panellastmovie);
    lv_imgbtn_set_src(ui_ImgButtonlong3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_663419717, NULL);

    lv_obj_set_width(ui_ImgButtonlong3, 200);
    lv_obj_set_height(ui_ImgButtonlong3, 130);
    lv_obj_set_x(ui_ImgButtonlong3, 248);
    lv_obj_set_y(ui_ImgButtonlong3, -20);
    lv_obj_set_align(ui_ImgButtonlong3, LV_ALIGN_CENTER);

    ui_ImgButtonlong2 = lv_imgbtn_create(ui_Panellastmovie);
    lv_imgbtn_set_src(ui_ImgButtonlong2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_663420742, NULL);
  
    lv_obj_set_width(ui_ImgButtonlong2, 200);
    lv_obj_set_height(ui_ImgButtonlong2, 130);
    lv_obj_set_x(ui_ImgButtonlong2, -7);
    lv_obj_set_y(ui_ImgButtonlong2, -16);
    lv_obj_set_align(ui_ImgButtonlong2, LV_ALIGN_CENTER);

    ui_ImgButtonlong1 = lv_imgbtn_create(ui_Panellastmovie);
    lv_imgbtn_set_src(ui_ImgButtonlong1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_663413319, NULL);
 
    lv_obj_set_width(ui_ImgButtonlong1, 200);
    lv_obj_set_height(ui_ImgButtonlong1, 130);
    lv_obj_set_x(ui_ImgButtonlong1, -272);
    lv_obj_set_y(ui_ImgButtonlong1, -11);
    lv_obj_set_align(ui_ImgButtonlong1, LV_ALIGN_CENTER);

    ui_Labellong1 = lv_label_create(ui_Panellastmovie);
    lv_obj_set_width(ui_Labellong1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labellong1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labellong1, -277);
    lv_obj_set_y(ui_Labellong1, 68);
    lv_obj_set_align(ui_Labellong1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labellong1, "龙1");
    lv_obj_set_style_text_font(ui_Labellong1, &ui_font_zzzz30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labellong2 = lv_label_create(ui_Panellastmovie);
    lv_obj_set_width(ui_Labellong2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labellong2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labellong2, -11);
    lv_obj_set_y(ui_Labellong2, 67);
    lv_obj_set_align(ui_Labellong2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labellong2, "龙2");
    lv_obj_set_style_text_font(ui_Labellong2, &ui_font_zzzz30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labellong3 = lv_label_create(ui_Panellastmovie);
    lv_obj_set_width(ui_Labellong3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labellong3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labellong3, 246);
    lv_obj_set_y(ui_Labellong3, 61);
    lv_obj_set_align(ui_Labellong3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labellong3, "龙3");
    lv_obj_set_style_text_font(ui_Labellong3, &ui_font_zzzz30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labellong4 = lv_label_create(ui_Panellastmovie);
    lv_obj_set_width(ui_Labellong4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labellong4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labellong4, 508);
    lv_obj_set_y(ui_Labellong4, 62);
    lv_obj_set_align(ui_Labellong4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labellong4, "龙4");
    lv_obj_set_style_text_font(ui_Labellong4, &ui_font_zzzz30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hotmovie = lv_label_create(ui_Panelmianban);
    lv_obj_set_width(ui_hotmovie, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hotmovie, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hotmovie, -321);
    lv_obj_set_y(ui_hotmovie, -183);
    lv_obj_set_align(ui_hotmovie, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hotmovie, "热映电影：");
    lv_obj_set_style_text_font(ui_hotmovie, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_latsmovie = lv_label_create(ui_Panelmianban);
    lv_obj_set_width(ui_latsmovie, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_latsmovie, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_latsmovie, -318);
    lv_obj_set_y(ui_latsmovie, 22);
    lv_obj_set_align(ui_latsmovie, LV_ALIGN_CENTER);
    lv_label_set_text(ui_latsmovie, "待映电影：");
    lv_obj_set_style_text_font(ui_latsmovie, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panelyanchu = lv_obj_create(ui_Panelmianban);
    lv_obj_set_width(ui_Panelyanchu, 763);
    lv_obj_set_height(ui_Panelyanchu, 160);
    lv_obj_set_x(ui_Panelyanchu, -12);
    lv_obj_set_y(ui_Panelyanchu, 399);
    lv_obj_set_align(ui_Panelyanchu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panelyanchu, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Panelyanchu, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Panelyanchu, LV_DIR_HOR);

    ui_ImgButtonnaiman = lv_imgbtn_create(ui_Panelyanchu);
    lv_imgbtn_set_src(ui_ImgButtonnaiman, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_280646667, NULL);
   
    lv_obj_set_width(ui_ImgButtonnaiman, 200);
    lv_obj_set_height(ui_ImgButtonnaiman, 130);
    lv_obj_set_x(ui_ImgButtonnaiman, -266);
    lv_obj_set_y(ui_ImgButtonnaiman, -6);
    lv_obj_set_align(ui_ImgButtonnaiman, LV_ALIGN_CENTER);

    ui_ImgButtonlpl = lv_imgbtn_create(ui_Panelyanchu);
    lv_imgbtn_set_src(ui_ImgButtonlpl, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lpl_png, NULL);
   
    lv_obj_set_width(ui_ImgButtonlpl, 200);
    lv_obj_set_height(ui_ImgButtonlpl, 130);
    lv_obj_set_x(ui_ImgButtonlpl, 4);
    lv_obj_set_y(ui_ImgButtonlpl, -5);
    lv_obj_set_align(ui_ImgButtonlpl, LV_ALIGN_CENTER);

    ui_Labellpl = lv_label_create(ui_Panelyanchu);
    lv_obj_set_width(ui_Labellpl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labellpl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labellpl, -11);
    lv_obj_set_y(ui_Labellpl, 77);
    lv_obj_set_align(ui_Labellpl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labellpl, "LPL");
    lv_obj_set_style_text_font(ui_Labellpl, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelnaiwan = lv_label_create(ui_Panelyanchu);
    lv_obj_set_width(ui_Labelnaiwan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelnaiwan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelnaiwan, -262);
    lv_obj_set_y(ui_Labelnaiwan, 80);
    lv_obj_set_align(ui_Labelnaiwan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelnaiwan, "乃万");
    lv_obj_set_style_text_font(ui_Labelnaiwan, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelyanchu = lv_label_create(ui_Panelmianban);
    lv_obj_set_width(ui_Labelyanchu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelyanchu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelyanchu, -313);
    lv_obj_set_y(ui_Labelyanchu, 292);
    lv_obj_set_align(ui_Labelyanchu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelyanchu, "热门演出：");
    lv_obj_set_style_text_font(ui_Labelyanchu, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_movie);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 538);
    lv_obj_set_height(ui_Container7, 25);
    lv_obj_set_x(ui_Container7, -126);
    lv_obj_set_y(ui_Container7, 227);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container7, lv_color_hex(0x666060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container7, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container7, lv_color_hex(0x544C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labeldate = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Labeldate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeldate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Labeldate, LV_ALIGN_CENTER);
    date1(ui_Labeldate);
    lv_obj_set_style_text_color(ui_Labeldate, lv_color_hex(0x140505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labeldate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labeldate, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelday = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Labelday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelday, 15);
    lv_obj_set_y(ui_Labelday, -1);
    lv_obj_set_align(ui_Labelday, LV_ALIGN_CENTER);
    week1(ui_Labelday);
    lv_obj_set_style_text_color(ui_Labelday, lv_color_hex(0x00FF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelday, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelweather = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Labelweather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelweather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelweather, 37);
    lv_obj_set_y(ui_Labelweather, -1);
    lv_obj_set_align(ui_Labelweather, LV_ALIGN_CENTER);
    weather1(ui_Labelweather);
    lv_obj_set_style_text_color(ui_Labelweather, lv_color_hex(0xFEF600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelweather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelweather, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelminutie = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Labelminutie, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelminutie, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelminutie, 22);
    lv_obj_set_y(ui_Labelminutie, 0);
    lv_obj_set_align(ui_Labelminutie, LV_ALIGN_CENTER);
    clock1(ui_Labelminutie);
    lv_obj_set_style_text_color(ui_Labelminutie, lv_color_hex(0x00DBFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelminutie, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelminutie, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Buttonyinyuan, ui_event_Buttonyinyuan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonpig, ui_event_ImgButtonpig, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtoncow, ui_event_ImgButtoncow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtondog, ui_event_ImgButtondog, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonggbond, ui_event_ImgButtonggbond, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonlong4, ui_event_ImgButtonlong4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonlong3, ui_event_ImgButtonlong3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonlong2, ui_event_ImgButtonlong2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonlong1, ui_event_ImgButtonlong1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonnaiman, ui_event_ImgButtonnaiman, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButtonlpl, ui_event_ImgButtonlpl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_movie, ui_event_movie, LV_EVENT_ALL, NULL);

}
