// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: yingyuan

#include "../ui.h"

//充值面板事件（实现在 ui_event_tmp.c）
extern void ui_event_recharge(lv_event_t * e);

void ui_mine_screen_init(void)
{
    ui_mine = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mine, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container12 = lv_obj_create(ui_mine);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 538);
    lv_obj_set_height(ui_Container12, 37);
    lv_obj_set_x(ui_Container12, -127);
    lv_obj_set_y(ui_Container12, -210);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container12, lv_color_hex(0x666060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container12, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container12, lv_color_hex(0x544C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label74 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label74, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label74, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label74, LV_ALIGN_CENTER);
    date1(ui_Label74);
    lv_obj_set_style_text_color(ui_Label74, lv_color_hex(0x0A0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label74, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label74, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label75 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label75, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label75, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label75, 15);
    lv_obj_set_y(ui_Label75, -1);
    lv_obj_set_align(ui_Label75, LV_ALIGN_CENTER);
    week1(ui_Label75);
    lv_obj_set_style_text_color(ui_Label75, lv_color_hex(0x00FF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label75, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label75, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label76 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label76, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label76, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label76, 37);
    lv_obj_set_y(ui_Label76, -1);
    lv_obj_set_align(ui_Label76, LV_ALIGN_CENTER);
    weather1(ui_Label76);
    lv_obj_set_style_text_color(ui_Label76, lv_color_hex(0xF000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label76, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label76, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label77 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label77, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label77, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label77, 22);
    lv_obj_set_y(ui_Label77, 0);
    lv_obj_set_align(ui_Label77, LV_ALIGN_CENTER);
    clock1(ui_Label77);
    lv_obj_set_style_text_color(ui_Label77, lv_color_hex(0x00DBFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label77, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label77, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_mine);
    lv_obj_set_width(ui_Panel12, 785);
    lv_obj_set_height(ui_Panel12, 184);
    lv_obj_set_x(ui_Panel12, 0);
    lv_obj_set_y(ui_Panel12, -39);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label40 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label40, -310);
    lv_obj_set_y(ui_Label40, -68);
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, "我的订单");
    lv_obj_set_style_text_font(ui_Label40, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_piao = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_piao, &ui_img_1523300687);  //电影票图标：查看订单
    lv_obj_set_width(ui_piao, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_piao, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_piao, 97);
    lv_obj_set_y(ui_piao, 25);
    lv_obj_set_align(ui_piao, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_piao, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_piao, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_return = lv_btn_create(ui_mine);
    lv_obj_set_width(ui_return, 100);
    lv_obj_set_height(ui_return, 50);
    lv_obj_set_x(ui_return, -327);
    lv_obj_set_y(ui_return, 134);
    lv_obj_set_align(ui_return, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_return, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_return, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_return, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_return, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label78 = lv_label_create(ui_return);
    lv_obj_set_width(ui_Label78, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label78, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label78, 1);
    lv_obj_set_y(ui_Label78, 0);
    lv_obj_set_align(ui_Label78, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label78, "退出");
    lv_obj_set_style_text_color(ui_Label78, lv_color_hex(0xEEE1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label78, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label78, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_mine);
    lv_img_set_src(ui_Image5, &ui_img_1152922109);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 276);
    lv_obj_set_y(ui_Image5, -183);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel13 = lv_obj_create(ui_mine);
    lv_obj_set_width(ui_Panel13, 175);
    lv_obj_set_height(ui_Panel13, 171);
    lv_obj_set_x(ui_Panel13, 277);
    lv_obj_set_y(ui_Panel13, 140);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label79 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label79, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label79, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label79, 14);
    lv_obj_set_y(ui_Label79, 4);
    lv_obj_set_align(ui_Label79, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label79, "我的余额:   \n      \n     0元\n\n");
    lv_obj_set_style_text_font(ui_Label79, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return2 = lv_btn_create(ui_mine);
    lv_obj_set_width(ui_return2, 100);
    lv_obj_set_height(ui_return2, 50);
    lv_obj_set_x(ui_return2, -192);
    lv_obj_set_y(ui_return2, 135);
    lv_obj_set_align(ui_return2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_return2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_return2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_return2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_return2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label81 = lv_label_create(ui_return2);
    lv_obj_set_width(ui_Label81, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label81, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label81, 1);
    lv_obj_set_y(ui_Label81, 0);
    lv_obj_set_align(ui_Label81, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label81, "返回");
    lv_obj_set_style_text_color(ui_Label81, lv_color_hex(0xEEE1E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label81, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label81, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_piao, ui_event_piao, LV_EVENT_ALL, NULL);
  
    lv_obj_add_event_cb(ui_return, ui_event_return, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_return2, ui_event_return2, LV_EVENT_ALL, NULL);

    //点击余额区域弹出充值面板
    lv_obj_add_flag(ui_Panel13, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(ui_Panel13, ui_event_recharge, LV_EVENT_ALL, NULL);

}
