// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: yingyuan

#include "../ui.h"

void ui_selectseat_screen_init(void)
{
    ui_selectseat = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_selectseat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel7 = lv_obj_create(ui_selectseat);
    lv_obj_set_width(ui_Panel7, 800);
    lv_obj_set_height(ui_Panel7, 60);
    lv_obj_set_x(ui_Panel7, 0);
    lv_obj_set_y(ui_Panel7, -209);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xAA9E9E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_moviename = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_moviename, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_moviename, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_moviename, -327);
    lv_obj_set_y(ui_moviename, 3);
    lv_obj_set_align(ui_moviename, LV_ALIGN_CENTER);
    lv_label_set_text(ui_moviename, "电影名：--");
    lv_obj_set_style_text_font(ui_moviename, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, -17);
    lv_obj_set_y(ui_date, 1);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    week1(ui_date);
    lv_obj_set_style_text_font(ui_date, &ui_font_zzzz30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_selectseat);
    lv_obj_set_width(ui_Panel8, 800);
    lv_obj_set_height(ui_Panel8, 309);
    lv_obj_set_x(ui_Panel8, -3);
    lv_obj_set_y(ui_Panel8, -26);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Panel8, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Panel8, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xA59B9B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hang1 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_hang1, 785);
    lv_obj_set_height(ui_hang1, 50);
    lv_obj_set_x(ui_hang1, -2);
    lv_obj_set_y(ui_hang1, -121);
    lv_obj_set_align(ui_hang1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hang1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

     ui_hang2 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_hang2, 785);
    lv_obj_set_height(ui_hang2, 50);
    lv_obj_set_x(ui_hang2, -1);
    lv_obj_set_y(ui_hang2, -62);
    lv_obj_set_align(ui_hang2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hang2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

     ui_hang3 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_hang3, 785);
    lv_obj_set_height(ui_hang3, 50);
    lv_obj_set_x(ui_hang3, 0);
    lv_obj_set_y(ui_hang3, -5);
    lv_obj_set_align(ui_hang3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hang3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hang4 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_hang4, 785);
    lv_obj_set_height(ui_hang4, 50);
    lv_obj_set_x(ui_hang4, -8);
    lv_obj_set_y(ui_hang4, 53);
    lv_obj_set_align(ui_hang4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hang4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

     ui_hang5 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_hang5, 785);
    lv_obj_set_height(ui_hang5, 50);
    lv_obj_set_x(ui_hang5, -7);
    lv_obj_set_y(ui_hang5, 110);
    lv_obj_set_align(ui_hang5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hang5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_seat11 = lv_btn_create(ui_hang2);
    lv_obj_set_width(ui_seat11, 36);
    lv_obj_set_height(ui_seat11, 36);
    lv_obj_set_x(ui_seat11, -335);
    lv_obj_set_y(ui_seat11, -2);
    lv_obj_set_align(ui_seat11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat13 = lv_btn_create(ui_hang2);
    lv_obj_set_width(ui_seat13, 36);
    lv_obj_set_height(ui_seat13, 36);
    lv_obj_set_x(ui_seat13, -178);
    lv_obj_set_y(ui_seat13, -1);
    lv_obj_set_align(ui_seat13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat14 = lv_btn_create(ui_hang2);
    lv_obj_set_width(ui_seat14, 36);
    lv_obj_set_height(ui_seat14, 36);
    lv_obj_set_x(ui_seat14, -104);
    lv_obj_set_y(ui_seat14, -2);
    lv_obj_set_align(ui_seat14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat15 = lv_btn_create(ui_hang2);
    lv_obj_set_width(ui_seat15, 36);
    lv_obj_set_height(ui_seat15, 36);
    lv_obj_set_x(ui_seat15, -26);
    lv_obj_set_y(ui_seat15, -4);
    lv_obj_set_align(ui_seat15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat16 = lv_btn_create(ui_hang2);
    lv_obj_set_width(ui_seat16, 36);
    lv_obj_set_height(ui_seat16, 36);
    lv_obj_set_x(ui_seat16, 47);
    lv_obj_set_y(ui_seat16, 1);
    lv_obj_set_align(ui_seat16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat16, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat17 = lv_btn_create(ui_hang2);
    lv_obj_set_width(ui_seat17, 36);
    lv_obj_set_height(ui_seat17, 36);
    lv_obj_set_x(ui_seat17, 109);
    lv_obj_set_y(ui_seat17, -2);
    lv_obj_set_align(ui_seat17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat17, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat18 = lv_btn_create(ui_hang2);
    lv_obj_set_width(ui_seat18, 36);
    lv_obj_set_height(ui_seat18, 36);
    lv_obj_set_x(ui_seat18, 178);
    lv_obj_set_y(ui_seat18, 1);
    lv_obj_set_align(ui_seat18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat18, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat19 = lv_btn_create(ui_hang2);
    lv_obj_set_width(ui_seat19, 36);
    lv_obj_set_height(ui_seat19, 36);
    lv_obj_set_x(ui_seat19, 244);
    lv_obj_set_y(ui_seat19, 2);
    lv_obj_set_align(ui_seat19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat19, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat20 = lv_btn_create(ui_hang2);
    lv_obj_set_width(ui_seat20, 36);
    lv_obj_set_height(ui_seat20, 36);
    lv_obj_set_x(ui_seat20, 315);
    lv_obj_set_y(ui_seat20, -1);
    lv_obj_set_align(ui_seat20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat12 = lv_btn_create(ui_hang2);
    lv_obj_set_width(ui_seat12, 36);
    lv_obj_set_height(ui_seat12, 36);
    lv_obj_set_x(ui_seat12, -255);
    lv_obj_set_y(ui_seat12, -2);
    lv_obj_set_align(ui_seat12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel9 = lv_obj_create(ui_selectseat);
    lv_obj_set_width(ui_Panel9, 800);
    lv_obj_set_height(ui_Panel9, 60);
    lv_obj_set_x(ui_Panel9, -2);
    lv_obj_set_y(ui_Panel9, 164);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xBEBCBC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_total = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_total, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_total, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_total, -75);
    lv_obj_set_y(ui_total, 1);
    lv_obj_set_align(ui_total, LV_ALIGN_CENTER);
    lv_label_set_text(ui_total, "合计： 0元");
    lv_obj_set_style_text_font(ui_total, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_number, -321);
    lv_obj_set_y(ui_number, 1);
    lv_obj_set_align(ui_number, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number, "已选：0 张");
    lv_obj_set_style_text_font(ui_number, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Panel9);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 304);
    lv_obj_set_y(ui_Button3, 2);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFF0035), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 1);
    lv_obj_set_y(ui_Label26, 0);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "去支付");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x160303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

   

    ui_seat10 = lv_btn_create(ui_hang1);
    lv_obj_set_width(ui_seat10, 36);
    lv_obj_set_height(ui_seat10, 36);
    lv_obj_set_x(ui_seat10, 314);
    lv_obj_set_y(ui_seat10, -1);
    lv_obj_set_align(ui_seat10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat1 = lv_btn_create(ui_hang1);
    lv_obj_set_width(ui_seat1, 36);
    lv_obj_set_height(ui_seat1, 36);
    lv_obj_set_x(ui_seat1, -338);
    lv_obj_set_y(ui_seat1, -3);
    lv_obj_set_align(ui_seat1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat2 = lv_btn_create(ui_hang1);
    lv_obj_set_width(ui_seat2, 36);
    lv_obj_set_height(ui_seat2, 36);
    lv_obj_set_x(ui_seat2, -263);
    lv_obj_set_y(ui_seat2, -2);
    lv_obj_set_align(ui_seat2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat3 = lv_btn_create(ui_hang1);
    lv_obj_set_width(ui_seat3, 36);
    lv_obj_set_height(ui_seat3, 36);
    lv_obj_set_x(ui_seat3, -183);
    lv_obj_set_y(ui_seat3, -3);
    lv_obj_set_align(ui_seat3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat4 = lv_btn_create(ui_hang1);
    lv_obj_set_width(ui_seat4, 36);
    lv_obj_set_height(ui_seat4, 36);
    lv_obj_set_x(ui_seat4, -114);
    lv_obj_set_y(ui_seat4, -4);
    lv_obj_set_align(ui_seat4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat5 = lv_btn_create(ui_hang1);
    lv_obj_set_width(ui_seat5, 36);
    lv_obj_set_height(ui_seat5, 36);
    lv_obj_set_x(ui_seat5, -35);
    lv_obj_set_y(ui_seat5, -4);
    lv_obj_set_align(ui_seat5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat6 = lv_btn_create(ui_hang1);
    lv_obj_set_width(ui_seat6, 36);
    lv_obj_set_height(ui_seat6, 36);
    lv_obj_set_x(ui_seat6, 38);
    lv_obj_set_y(ui_seat6, -4);
    lv_obj_set_align(ui_seat6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat7 = lv_btn_create(ui_hang1);
    lv_obj_set_width(ui_seat7, 36);
    lv_obj_set_height(ui_seat7, 36);
    lv_obj_set_x(ui_seat7, 111);
    lv_obj_set_y(ui_seat7, -3);
    lv_obj_set_align(ui_seat7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat8 = lv_btn_create(ui_hang1);
    lv_obj_set_width(ui_seat8, 36);
    lv_obj_set_height(ui_seat8, 36);
    lv_obj_set_x(ui_seat8, 176);
    lv_obj_set_y(ui_seat8, -1);
    lv_obj_set_align(ui_seat8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat9 = lv_btn_create(ui_hang1);
    lv_obj_set_width(ui_seat9, 36);
    lv_obj_set_height(ui_seat9, 36);
    lv_obj_set_x(ui_seat9, 236);
    lv_obj_set_y(ui_seat9, 0);
    lv_obj_set_align(ui_seat9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

   

    ui_seat30 = lv_btn_create(ui_hang3);
    lv_obj_set_width(ui_seat30, 36);
    lv_obj_set_height(ui_seat30, 36);
    lv_obj_set_x(ui_seat30, 311);
    lv_obj_set_y(ui_seat30, -2);
    lv_obj_set_align(ui_seat30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat30, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat21 = lv_btn_create(ui_hang3);
    lv_obj_set_width(ui_seat21, 36);
    lv_obj_set_height(ui_seat21, 36);
    lv_obj_set_x(ui_seat21, -345);
    lv_obj_set_y(ui_seat21, -4);
    lv_obj_set_align(ui_seat21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat22 = lv_btn_create(ui_hang3);
    lv_obj_set_width(ui_seat22, 36);
    lv_obj_set_height(ui_seat22, 36);
    lv_obj_set_x(ui_seat22, -259);
    lv_obj_set_y(ui_seat22, -2);
    lv_obj_set_align(ui_seat22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat23 = lv_btn_create(ui_hang3);
    lv_obj_set_width(ui_seat23, 36);
    lv_obj_set_height(ui_seat23, 36);
    lv_obj_set_x(ui_seat23, -182);
    lv_obj_set_y(ui_seat23, 0);
    lv_obj_set_align(ui_seat23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat24 = lv_btn_create(ui_hang3);
    lv_obj_set_width(ui_seat24, 36);
    lv_obj_set_height(ui_seat24, 36);
    lv_obj_set_x(ui_seat24, -106);
    lv_obj_set_y(ui_seat24, -2);
    lv_obj_set_align(ui_seat24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat25 = lv_btn_create(ui_hang3);
    lv_obj_set_width(ui_seat25, 36);
    lv_obj_set_height(ui_seat25, 36);
    lv_obj_set_x(ui_seat25, -34);
    lv_obj_set_y(ui_seat25, -2);
    lv_obj_set_align(ui_seat25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat26 = lv_btn_create(ui_hang3);
    lv_obj_set_width(ui_seat26, 36);
    lv_obj_set_height(ui_seat26, 36);
    lv_obj_set_x(ui_seat26, 45);
    lv_obj_set_y(ui_seat26, -3);
    lv_obj_set_align(ui_seat26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat26, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat27 = lv_btn_create(ui_hang3);
    lv_obj_set_width(ui_seat27, 36);
    lv_obj_set_height(ui_seat27, 36);
    lv_obj_set_x(ui_seat27, 110);
    lv_obj_set_y(ui_seat27, -5);
    lv_obj_set_align(ui_seat27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat27, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat28 = lv_btn_create(ui_hang3);
    lv_obj_set_width(ui_seat28, 36);
    lv_obj_set_height(ui_seat28, 36);
    lv_obj_set_x(ui_seat28, 177);
    lv_obj_set_y(ui_seat28, -1);
    lv_obj_set_align(ui_seat28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat28, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat29 = lv_btn_create(ui_hang3);
    lv_obj_set_width(ui_seat29, 36);
    lv_obj_set_height(ui_seat29, 38);
    lv_obj_set_x(ui_seat29, 239);
    lv_obj_set_y(ui_seat29, -3);
    lv_obj_set_align(ui_seat29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat29, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    

    ui_seat31 = lv_btn_create(ui_hang4);
    lv_obj_set_width(ui_seat31, 36);
    lv_obj_set_height(ui_seat31, 36);
    lv_obj_set_x(ui_seat31, -335);
    lv_obj_set_y(ui_seat31, -2);
    lv_obj_set_align(ui_seat31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat32 = lv_btn_create(ui_hang4);
    lv_obj_set_width(ui_seat32, 36);
    lv_obj_set_height(ui_seat32, 36);
    lv_obj_set_x(ui_seat32, -252);
    lv_obj_set_y(ui_seat32, -3);
    lv_obj_set_align(ui_seat32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat32, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat33 = lv_btn_create(ui_hang4);
    lv_obj_set_width(ui_seat33, 36);
    lv_obj_set_height(ui_seat33, 36);
    lv_obj_set_x(ui_seat33, -172);
    lv_obj_set_y(ui_seat33, -4);
    lv_obj_set_align(ui_seat33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat33, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat34 = lv_btn_create(ui_hang4);
    lv_obj_set_width(ui_seat34, 36);
    lv_obj_set_height(ui_seat34, 36);
    lv_obj_set_x(ui_seat34, -100);
    lv_obj_set_y(ui_seat34, -4);
    lv_obj_set_align(ui_seat34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat34, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat35 = lv_btn_create(ui_hang4);
    lv_obj_set_width(ui_seat35, 36);
    lv_obj_set_height(ui_seat35, 36);
    lv_obj_set_x(ui_seat35, -29);
    lv_obj_set_y(ui_seat35, -3);
    lv_obj_set_align(ui_seat35, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat35, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat36 = lv_btn_create(ui_hang4);
    lv_obj_set_width(ui_seat36, 36);
    lv_obj_set_height(ui_seat36, 36);
    lv_obj_set_x(ui_seat36, 52);
    lv_obj_set_y(ui_seat36, -2);
    lv_obj_set_align(ui_seat36, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat36, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat37 = lv_btn_create(ui_hang4);
    lv_obj_set_width(ui_seat37, 36);
    lv_obj_set_height(ui_seat37, 36);
    lv_obj_set_x(ui_seat37, 119);
    lv_obj_set_y(ui_seat37, -1);
    lv_obj_set_align(ui_seat37, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat37, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat38 = lv_btn_create(ui_hang4);
    lv_obj_set_width(ui_seat38, 36);
    lv_obj_set_height(ui_seat38, 36);
    lv_obj_set_x(ui_seat38, 188);
    lv_obj_set_y(ui_seat38, 0);
    lv_obj_set_align(ui_seat38, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat38, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat39 = lv_btn_create(ui_hang4);
    lv_obj_set_width(ui_seat39, 36);
    lv_obj_set_height(ui_seat39, 36);
    lv_obj_set_x(ui_seat39, 248);
    lv_obj_set_y(ui_seat39, 2);
    lv_obj_set_align(ui_seat39, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat39, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat40 = lv_btn_create(ui_hang4);
    lv_obj_set_width(ui_seat40, 36);
    lv_obj_set_height(ui_seat40, 36);
    lv_obj_set_x(ui_seat40, 318);
    lv_obj_set_y(ui_seat40, -2);
    lv_obj_set_align(ui_seat40, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat40, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

   
    ui_seat41 = lv_btn_create(ui_hang5);
    lv_obj_set_width(ui_seat41, 36);
    lv_obj_set_height(ui_seat41, 36);
    lv_obj_set_x(ui_seat41, -335);
    lv_obj_set_y(ui_seat41, -2);
    lv_obj_set_align(ui_seat41, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat41, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat42 = lv_btn_create(ui_hang5);
    lv_obj_set_width(ui_seat42, 36);
    lv_obj_set_height(ui_seat42, 36);
    lv_obj_set_x(ui_seat42, -248);
    lv_obj_set_y(ui_seat42, -5);
    lv_obj_set_align(ui_seat42, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat42, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat43 = lv_btn_create(ui_hang5);
    lv_obj_set_width(ui_seat43, 36);
    lv_obj_set_height(ui_seat43, 36);
    lv_obj_set_x(ui_seat43, -175);
    lv_obj_set_y(ui_seat43, -5);
    lv_obj_set_align(ui_seat43, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat43, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat44 = lv_btn_create(ui_hang5);
    lv_obj_set_width(ui_seat44, 36);
    lv_obj_set_height(ui_seat44, 36);
    lv_obj_set_x(ui_seat44, -100);
    lv_obj_set_y(ui_seat44, -3);
    lv_obj_set_align(ui_seat44, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat44, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat44, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat45 = lv_btn_create(ui_hang5);
    lv_obj_set_width(ui_seat45, 36);
    lv_obj_set_height(ui_seat45, 36);
    lv_obj_set_x(ui_seat45, -27);
    lv_obj_set_y(ui_seat45, 0);
    lv_obj_set_align(ui_seat45, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat45, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat46 = lv_btn_create(ui_hang5);
    lv_obj_set_width(ui_seat46, 36);
    lv_obj_set_height(ui_seat46, 36);
    lv_obj_set_x(ui_seat46, 51);
    lv_obj_set_y(ui_seat46, -3);
    lv_obj_set_align(ui_seat46, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat46, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat47 = lv_btn_create(ui_hang5);
    lv_obj_set_width(ui_seat47, 36);
    lv_obj_set_height(ui_seat47, 36);
    lv_obj_set_x(ui_seat47, 122);
    lv_obj_set_y(ui_seat47, 2);
    lv_obj_set_align(ui_seat47, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat47, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat47, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat48 = lv_btn_create(ui_hang5);
    lv_obj_set_width(ui_seat48, 36);
    lv_obj_set_height(ui_seat48, 36);
    lv_obj_set_x(ui_seat48, 193);
    lv_obj_set_y(ui_seat48, 1);
    lv_obj_set_align(ui_seat48, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat48, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat48, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat49 = lv_btn_create(ui_hang5);
    lv_obj_set_width(ui_seat49, 36);
    lv_obj_set_height(ui_seat49, 36);
    lv_obj_set_x(ui_seat49, 257);
    lv_obj_set_y(ui_seat49, 1);
    lv_obj_set_align(ui_seat49, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat49, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat49, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_seat50 = lv_btn_create(ui_hang5);
    lv_obj_set_width(ui_seat50, 36);
    lv_obj_set_height(ui_seat50, 36);
    lv_obj_set_x(ui_seat50, 322);
    lv_obj_set_y(ui_seat50, 3);
    lv_obj_set_align(ui_seat50, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_seat50, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_seat50, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_selectseat);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 538);
    lv_obj_set_height(ui_Container9, 25);
    lv_obj_set_x(ui_Container9, -112);
    lv_obj_set_y(ui_Container9, 220);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container9, lv_color_hex(0x666060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container9, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container9, lv_color_hex(0x544C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label62 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label62, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label62, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label62, LV_ALIGN_CENTER);
    date1(ui_Label62);
    lv_obj_set_style_text_color(ui_Label62, lv_color_hex(0x130505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label62, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label62, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label63 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label63, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label63, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label63, 15);
    lv_obj_set_y(ui_Label63, -1);
    lv_obj_set_align(ui_Label63, LV_ALIGN_CENTER);
    week1(ui_Label63);
    lv_obj_set_style_text_color(ui_Label63, lv_color_hex(0x00FF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label63, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label63, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label64 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label64, 37);
    lv_obj_set_y(ui_Label64, -1);
    lv_obj_set_align(ui_Label64, LV_ALIGN_CENTER);
    weather1(ui_Label64);
    lv_obj_set_style_text_color(ui_Label64, lv_color_hex(0xFEF600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label64, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label64, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label65 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label65, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label65, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label65, 22);
    lv_obj_set_y(ui_Label65, 0);
    lv_obj_set_align(ui_Label65, LV_ALIGN_CENTER);
    clock1(ui_Label65);
    lv_obj_set_style_text_color(ui_Label65, lv_color_hex(0x00DBFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label65, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label65, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buynumber = lv_dropdown_create(ui_selectseat);
    lv_dropdown_set_options(ui_buynumber, "购票人数：\n1 人\n2 人\n3 人\n4 人\n5 人");
    lv_obj_set_width(ui_buynumber, 183);
    lv_obj_set_height(ui_buynumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_buynumber, 302);
    lv_obj_set_y(ui_buynumber, -210);
    lv_obj_set_align(ui_buynumber, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buynumber, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_buynumber, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_buynumber, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_buynumber, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_buynumber, &ui_font_zti, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_buynumber), &ui_font_zti,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_seat11, ui_event_seat11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat13, ui_event_seat13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat14, ui_event_seat14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat15, ui_event_seat15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat16, ui_event_seat16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat17, ui_event_seat17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat18, ui_event_seat18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat19, ui_event_seat19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat20, ui_event_seat20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat12, ui_event_seat12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat10, ui_event_seat10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat1, ui_event_seat1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat2, ui_event_seat2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat3, ui_event_seat3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat4, ui_event_seat4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat5, ui_event_seat5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat6, ui_event_seat6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat7, ui_event_seat7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat8, ui_event_seat8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat9, ui_event_seat9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat30, ui_event_seat30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat21, ui_event_seat21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat22, ui_event_seat22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat23, ui_event_seat23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat24, ui_event_seat24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat25, ui_event_seat25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat26, ui_event_seat26, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat27, ui_event_seat27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat28, ui_event_seat28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat29, ui_event_seat29, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat31, ui_event_seat31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat32, ui_event_seat32, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat33, ui_event_seat33, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat34, ui_event_seat34, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat35, ui_event_seat35, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat36, ui_event_seat36, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat37, ui_event_seat37, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat38, ui_event_seat38, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat39, ui_event_seat39, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat40, ui_event_seat40, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat41, ui_event_seat41, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat42, ui_event_seat42, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat43, ui_event_seat43, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat44, ui_event_seat44, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat45, ui_event_seat45, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat46, ui_event_seat46, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat47, ui_event_seat47, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat48, ui_event_seat48, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat49, ui_event_seat49, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_seat50, ui_event_seat50, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buynumber, ui_event_buynumber, LV_EVENT_ALL, NULL);

    //统一处理已售座位（置灰 + 不可选中），不用给每个座位按钮单独加代码
    ui_apply_sold_seats();

}
