// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: yingyuan

#include "../ui.h"

void ui_yinyuan_screen_init(void)
{
    ui_yinyuan = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_yinyuan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_yinyuan);
    lv_obj_set_width(ui_Panel4, 800);
    lv_obj_set_height(ui_Panel4, 480);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Panel4, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Panel4, LV_DIR_VER);

    ui_ImgButton12 = lv_imgbtn_create(ui_Panel4);
    lv_imgbtn_set_src(ui_ImgButton12, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_145242593, NULL);

    lv_obj_set_width(ui_ImgButton12, 780);
    lv_obj_set_height(ui_ImgButton12, 300);
    lv_obj_set_x(ui_ImgButton12, -1);
    lv_obj_set_y(ui_ImgButton12, -92);
    lv_obj_set_align(ui_ImgButton12, LV_ALIGN_CENTER);

    ui_ImgButton13 = lv_imgbtn_create(ui_Panel4);
    lv_imgbtn_set_src(ui_ImgButton13, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_208404457, NULL);
  
    lv_obj_set_height(ui_ImgButton13, 300);
    lv_obj_set_width(ui_ImgButton13, LV_SIZE_CONTENT);   /// 780
    lv_obj_set_x(ui_ImgButton13, -3);
    lv_obj_set_y(ui_ImgButton13, 518);
    lv_obj_set_align(ui_ImgButton13, LV_ALIGN_CENTER);

    ui_ImgButton14 = lv_imgbtn_create(ui_Panel4);
    lv_imgbtn_set_src(ui_ImgButton14, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_873324722, NULL);
   
    lv_obj_set_height(ui_ImgButton14, 300);
    lv_obj_set_width(ui_ImgButton14, LV_SIZE_CONTENT);   /// 780
    lv_obj_set_x(ui_ImgButton14, 4);
    lv_obj_set_y(ui_ImgButton14, 206);
    lv_obj_set_align(ui_ImgButton14, LV_ALIGN_CENTER);

    ui_Container8 = lv_obj_create(ui_yinyuan);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 538);
    lv_obj_set_height(ui_Container8, 25);
    lv_obj_set_x(ui_Container8, 128);
    lv_obj_set_y(ui_Container8, -222);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container8, lv_color_hex(0x666060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container8, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container8, lv_color_hex(0x544C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label58 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label58, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label58, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label58, LV_ALIGN_CENTER);
    date1(ui_Label58);
    lv_obj_set_style_text_color(ui_Label58, lv_color_hex(0x070202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label58, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label58, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label59 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label59, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label59, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label59, 15);
    lv_obj_set_y(ui_Label59, -1);
    lv_obj_set_align(ui_Label59, LV_ALIGN_CENTER);
    week1(ui_Label59);
    lv_obj_set_style_text_color(ui_Label59, lv_color_hex(0x00FF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label59, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label59, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label60, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60, 37);
    lv_obj_set_y(ui_Label60, -1);
    lv_obj_set_align(ui_Label60, LV_ALIGN_CENTER);
    weather1(ui_Label60);
    lv_obj_set_style_text_color(ui_Label60, lv_color_hex(0xFEF600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label60, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label61 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label61, 22);
    lv_obj_set_y(ui_Label61, 0);
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    clock1(ui_Label61);
    lv_obj_set_style_text_color(ui_Label61, lv_color_hex(0x00DBFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label61, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ImgButton12, ui_event_ImgButton12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton13, ui_event_ImgButton13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton14, ui_event_ImgButton14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_yinyuan, ui_event_yinyuan, LV_EVENT_ALL, NULL);

}
