// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: yingyuan

#include "../ui.h"

void ui_yes_or_no_screen_init(void)
{
    ui_yes_or_no = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_yes_or_no, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_yes_or_no, &ui_img_startui_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yes = lv_btn_create(ui_yes_or_no);
    lv_obj_set_width(ui_yes, 200);
    lv_obj_set_height(ui_yes, 100);
    lv_obj_set_x(ui_yes, -109);
    lv_obj_set_y(ui_yes, 73);
    lv_obj_set_align(ui_yes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_yes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_yes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_yes, &ui_img_1373481471, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_yes, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_yes);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "BACK");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFF0038), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NO1 = lv_btn_create(ui_yes_or_no);
    lv_obj_set_width(ui_NO1, 200);
    lv_obj_set_height(ui_NO1, 100);
    lv_obj_set_x(ui_NO1, 113);
    lv_obj_set_y(ui_NO1, 71);
    lv_obj_set_align(ui_NO1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NO1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NO1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_NO1, &ui_img_373844247, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_NO1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "ENTER");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFF0046), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_zti, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_yes_or_no);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 538);
    lv_obj_set_height(ui_Container1, 25);
    lv_obj_set_x(ui_Container1, -127);
    lv_obj_set_y(ui_Container1, -229);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x666060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container1, lv_color_hex(0x544C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    date1(ui_Label33);   
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0xF3EBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label33, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 15);
    lv_obj_set_y(ui_Label34, -1);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    week1(ui_Label34);
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0x00FF24), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label34, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 37);
    lv_obj_set_y(ui_Label35, -1);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    weather1(ui_Label35);
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0xFEF600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 22);
    lv_obj_set_y(ui_Label36, 0);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    clock1(ui_Label36);
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0x00DBFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label36, &ui_font_yyyy22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_yes, ui_event_yes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NO1, ui_event_NO1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_yes_or_no, ui_event_yes_or_no, LV_EVENT_ALL, NULL);

}
