SET(SOURCES screens/ui_start.c
    screens/ui_yes_or_no.c
    screens/ui_movie.c
    screens/ui_food.c
    screens/ui_login.c
    screens/ui_regis.c
    screens/ui_guangao.c
    screens/ui_success.c
    screens/ui_mine.c
    screens/ui_yinyuan.c
    screens/ui_selectseat.c
    screens/ui_dingdan.c
    screens/ui_failed.c
    ui.c
    list.c
    time1.c
    components/ui_comp_hook.c
    ui_helpers.c
    ui_event.c
    images/ui_img_failed_png.c
    images/ui_img_startui_png.c
    images/ui_img_1373481471.c
    images/ui_img_373844247.c
    images/ui_img_pepepig_png.c
    images/ui_img_841450715.c
    images/ui_img_620000976.c
    images/ui_img_ggbond_png.c
    images/ui_img_663409996.c
    images/ui_img_663419717.c
    images/ui_img_663420742.c
    images/ui_img_663413319.c
    images/ui_img_280646667.c
    images/ui_img_lpl_png.c
    images/ui_img_ls_png.c
    images/ui_img_zxf_png.c
    images/ui_img_mx_png.c
    images/ui_img_man_png.c
    images/ui_img_1081085947.c
    images/ui_img_kfc_png.c
    images/ui_img_1482295748.c
    images/ui_img_1735873665.c
    images/ui_img_yyy_png.c
    images/ui_img_623033322.c
    images/ui_img_1698191276.c
    images/ui_img_697434260.c
    images/ui_img_1523300687.c
    images/ui_img_1152922109.c
    images/ui_img_145242593.c
    images/ui_img_208404457.c
    images/ui_img_873324722.c
    images/ui_img_player_png.c
    fonts/ui_font_zt2.c
    fonts/ui_font_zt3.c
    fonts/ui_font_zti.c
    fonts/ui_font_zzzz30.c
    fonts/ui_font_yyyy22.c
    fonts/ui_font_zti.c)

add_library(ui ${SOURCES})
