// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: yingyuan

#include "ui.h"
#include "ui_helpers.h"

//// 由 ui_event_tmp.c 提供的选票信息接口
void ui_select_movie(const char *name);   //记录点击的电影名
void ui_select_cinema(int price);         //记录影院票价并刷新选座页
void ui_confirm_tickets(void);            //选座页"去支付"：记录所选座位和票款
void ui_update_balance(void);             //向云端查询余额并刷新"我的"页面显示
extern char g_movie_name[64];             //当前选择的电影名
extern int  g_ticket_price;               //当前选择的票价（元/张）

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_failed
void ui_failed_screen_init(void);
lv_obj_t * ui_failed;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label16;

// SCREEN: ui_start
void ui_start_screen_init(void);
void ui_event_start(lv_event_t * e);
lv_obj_t * ui_start;
void ui_event_Image1(lv_event_t * e);
lv_obj_t * ui_Image1;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Label43;
lv_obj_t * ui_Label44;
lv_obj_t * ui_Label45;


// SCREEN: ui_yes_or_no
void ui_yes_or_no_screen_init(void);
void ui_event_yes_or_no(lv_event_t * e);
lv_obj_t * ui_yes_or_no;
void ui_event_yes(lv_event_t * e);
lv_obj_t * ui_yes;
lv_obj_t * ui_Label2;
void ui_event_NO1(lv_event_t * e);
lv_obj_t * ui_NO1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label33;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Label36;



// SCREEN: ui_movie
void ui_movie_screen_init(void);
void ui_event_movie(lv_event_t * e);
lv_obj_t * ui_movie;
lv_obj_t * ui_Panellan;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Labelcowmine;
void ui_event_Buttonyinyuan(lv_event_t * e);
lv_obj_t * ui_Buttonyinyuan;
lv_obj_t * ui_Labelyinyuan_;
lv_obj_t * ui_Buttonmovie;
lv_obj_t * ui_Labelmovie1;
lv_obj_t * ui_Panelmianban;
lv_obj_t * ui_Panelhotmovie;
void ui_event_ImgButtonpig(lv_event_t * e);
lv_obj_t * ui_ImgButtonpig;
void ui_event_ImgButtoncow(lv_event_t * e);
lv_obj_t * ui_ImgButtoncow;
lv_obj_t * ui_Labelcow;
void ui_event_ImgButtondog(lv_event_t * e);
lv_obj_t * ui_ImgButtondog;
lv_obj_t * ui_Labeldog;
void ui_event_ImgButtonggbond(lv_event_t * e);
lv_obj_t * ui_ImgButtonggbond;
lv_obj_t * ui_Labelggbond;
lv_obj_t * ui_Labelpig;
lv_obj_t * ui_Panellastmovie;
void ui_event_ImgButtonlong4(lv_event_t * e);
lv_obj_t * ui_ImgButtonlong4;
void ui_event_ImgButtonlong3(lv_event_t * e);
lv_obj_t * ui_ImgButtonlong3;
void ui_event_ImgButtonlong2(lv_event_t * e);
lv_obj_t * ui_ImgButtonlong2;
void ui_event_ImgButtonlong1(lv_event_t * e);
lv_obj_t * ui_ImgButtonlong1;
lv_obj_t * ui_Labellong1;
lv_obj_t * ui_Labellong2;
lv_obj_t * ui_Labellong3;
lv_obj_t * ui_Labellong4;
lv_obj_t * ui_hotmovie;
lv_obj_t * ui_latsmovie;
lv_obj_t * ui_Panelyanchu;
void ui_event_ImgButtonnaiman(lv_event_t * e);
lv_obj_t * ui_ImgButtonnaiman;
void ui_event_ImgButtonlpl(lv_event_t * e);
lv_obj_t * ui_ImgButtonlpl;
lv_obj_t * ui_Labellpl;
lv_obj_t * ui_Labelnaiwan;
lv_obj_t * ui_Labelyanchu;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Labeldate;
lv_obj_t * ui_Labelday;
lv_obj_t * ui_Labelweather;
lv_obj_t * ui_Labelminutie;


// SCREEN: ui_food
void ui_food_screen_init(void);
void ui_event_food(lv_event_t * e);
lv_obj_t * ui_food;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_total2;
lv_obj_t * ui_number2;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_ImgButton15;
lv_obj_t * ui_ImgButton16;
lv_obj_t * ui_ImgButton18;
lv_obj_t * ui_ImgButton17;
lv_obj_t * ui_ImgButton19;
lv_obj_t * ui_ImgButton20;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Label32;
void ui_event_jian1(lv_event_t * e);
lv_obj_t * ui_jian1;
void ui_event_add1(lv_event_t * e);
lv_obj_t * ui_add1;
void ui_event_jian3(lv_event_t * e);
lv_obj_t * ui_jian3;
void ui_event_jian4(lv_event_t * e);
lv_obj_t * ui_jian4;
void ui_event_jian5(lv_event_t * e);
lv_obj_t * ui_jian5;
void ui_event_jian6(lv_event_t * e);
lv_obj_t * ui_jian6;
void ui_event_jian2(lv_event_t * e);
lv_obj_t * ui_jian2;
void ui_event_add3(lv_event_t * e);
lv_obj_t * ui_add3;
void ui_event_add4(lv_event_t * e);
lv_obj_t * ui_add4;
void ui_event_add5(lv_event_t * e);
lv_obj_t * ui_add5;
void ui_event_add6(lv_event_t * e);
lv_obj_t * ui_add6;
void ui_event_add2(lv_event_t * e);
lv_obj_t * ui_add2;
lv_obj_t * ui_Container10;
lv_obj_t * ui_Label66;
lv_obj_t * ui_Label67;
lv_obj_t * ui_Label68;
lv_obj_t * ui_Label69;


// SCREEN: ui_login
void ui_login_screen_init(void);
void ui_event_login(lv_event_t * e);
lv_obj_t * ui_login;
void ui_event_username1(lv_event_t * e);
lv_obj_t * ui_username1;
void ui_event_passname(lv_event_t * e);
lv_obj_t * ui_passname;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label8;
lv_obj_t * ui_TextArea5;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label9;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Label47;
lv_obj_t * ui_Label48;
lv_obj_t * ui_Label49;


// SCREEN: ui_regis
void ui_regis_screen_init(void);
void ui_event_regis(lv_event_t * e);
lv_obj_t * ui_regis;
void ui_event_username2(lv_event_t * e);
lv_obj_t * ui_username2;
void ui_event_passname1(lv_event_t * e);
lv_obj_t * ui_passname1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_TextArea1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Keyboard2;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label50;
lv_obj_t * ui_Label51;
lv_obj_t * ui_Label52;
lv_obj_t * ui_Label53;


// SCREEN: ui_guangao
void ui_guangao_screen_init(void);
lv_obj_t * ui_guangao;
void ui_event_ImgButton1(lv_event_t * e);
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label39;


// SCREEN: ui_success
void ui_success_screen_init(void);
lv_obj_t * ui_success;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Container11;
lv_obj_t * ui_Label70;
lv_obj_t * ui_Label71;
lv_obj_t * ui_Label72;
lv_obj_t * ui_Label73;


// SCREEN: ui_mine
void ui_mine_screen_init(void);
lv_obj_t * ui_mine;
lv_obj_t * ui_Container12;
lv_obj_t * ui_Label74;
lv_obj_t * ui_Label75;
lv_obj_t * ui_Label76;
lv_obj_t * ui_Label77;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label40;
void ui_event_piao(lv_event_t * e);
lv_obj_t * ui_piao;

void ui_event_return(lv_event_t * e);
lv_obj_t * ui_return;
lv_obj_t * ui_Label78;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Label79;
void ui_event_return2(lv_event_t * e);
lv_obj_t * ui_return2;
lv_obj_t * ui_Label81;


// SCREEN: ui_yinyuan
void ui_yinyuan_screen_init(void);
void ui_event_yinyuan(lv_event_t * e);
lv_obj_t * ui_yinyuan;
lv_obj_t * ui_Panel4;
void ui_event_ImgButton12(lv_event_t * e);
lv_obj_t * ui_ImgButton12;
void ui_event_ImgButton13(lv_event_t * e);
lv_obj_t * ui_ImgButton13;
void ui_event_ImgButton14(lv_event_t * e);
lv_obj_t * ui_ImgButton14;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Label58;
lv_obj_t * ui_Label59;
lv_obj_t * ui_Label60;
lv_obj_t * ui_Label61;


// SCREEN: ui_selectseat
void ui_selectseat_screen_init(void);
lv_obj_t * ui_selectseat;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_moviename;
lv_obj_t * ui_date;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_hang2;
void ui_event_seat11(lv_event_t * e);
lv_obj_t * ui_seat11;
void ui_event_seat13(lv_event_t * e);
lv_obj_t * ui_seat13;
void ui_event_seat14(lv_event_t * e);
lv_obj_t * ui_seat14;
void ui_event_seat15(lv_event_t * e);
lv_obj_t * ui_seat15;
void ui_event_seat16(lv_event_t * e);
lv_obj_t * ui_seat16;
void ui_event_seat17(lv_event_t * e);
lv_obj_t * ui_seat17;
void ui_event_seat18(lv_event_t * e);
lv_obj_t * ui_seat18;
void ui_event_seat19(lv_event_t * e);
lv_obj_t * ui_seat19;
void ui_event_seat20(lv_event_t * e);
lv_obj_t * ui_seat20;
void ui_event_seat12(lv_event_t * e);
lv_obj_t * ui_seat12;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_total;
lv_obj_t * ui_number;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label26;
lv_obj_t * ui_hang1;
void ui_event_seat10(lv_event_t * e);
lv_obj_t * ui_seat10;
void ui_event_seat1(lv_event_t * e);
lv_obj_t * ui_seat1;
void ui_event_seat2(lv_event_t * e);
lv_obj_t * ui_seat2;
void ui_event_seat3(lv_event_t * e);
lv_obj_t * ui_seat3;
void ui_event_seat4(lv_event_t * e);
lv_obj_t * ui_seat4;
void ui_event_seat5(lv_event_t * e);
lv_obj_t * ui_seat5;
void ui_event_seat6(lv_event_t * e);
lv_obj_t * ui_seat6;
void ui_event_seat7(lv_event_t * e);
lv_obj_t * ui_seat7;
void ui_event_seat8(lv_event_t * e);
lv_obj_t * ui_seat8;
void ui_event_seat9(lv_event_t * e);
lv_obj_t * ui_seat9;
lv_obj_t * ui_hang3;
void ui_event_seat30(lv_event_t * e);
lv_obj_t * ui_seat30;
void ui_event_seat21(lv_event_t * e);
lv_obj_t * ui_seat21;
void ui_event_seat22(lv_event_t * e);
lv_obj_t * ui_seat22;
void ui_event_seat23(lv_event_t * e);
lv_obj_t * ui_seat23;
void ui_event_seat24(lv_event_t * e);
lv_obj_t * ui_seat24;
void ui_event_seat25(lv_event_t * e);
lv_obj_t * ui_seat25;
void ui_event_seat26(lv_event_t * e);
lv_obj_t * ui_seat26;
void ui_event_seat27(lv_event_t * e);
lv_obj_t * ui_seat27;
void ui_event_seat28(lv_event_t * e);
lv_obj_t * ui_seat28;
void ui_event_seat29(lv_event_t * e);
lv_obj_t * ui_seat29;
lv_obj_t * ui_hang4;
void ui_event_seat31(lv_event_t * e);
lv_obj_t * ui_seat31;
void ui_event_seat32(lv_event_t * e);
lv_obj_t * ui_seat32;
void ui_event_seat33(lv_event_t * e);
lv_obj_t * ui_seat33;
void ui_event_seat34(lv_event_t * e);
lv_obj_t * ui_seat34;
void ui_event_seat35(lv_event_t * e);
lv_obj_t * ui_seat35;
void ui_event_seat36(lv_event_t * e);
lv_obj_t * ui_seat36;
void ui_event_seat37(lv_event_t * e);
lv_obj_t * ui_seat37;
void ui_event_seat38(lv_event_t * e);
lv_obj_t * ui_seat38;
void ui_event_seat39(lv_event_t * e);
lv_obj_t * ui_seat39;
void ui_event_seat40(lv_event_t * e);
lv_obj_t * ui_seat40;
lv_obj_t * ui_hang5;
void ui_event_seat41(lv_event_t * e);
lv_obj_t * ui_seat41;
void ui_event_seat42(lv_event_t * e);
lv_obj_t * ui_seat42;
void ui_event_seat43(lv_event_t * e);
lv_obj_t * ui_seat43;
void ui_event_seat44(lv_event_t * e);
lv_obj_t * ui_seat44;
void ui_event_seat45(lv_event_t * e);
lv_obj_t * ui_seat45;
void ui_event_seat46(lv_event_t * e);
lv_obj_t * ui_seat46;
void ui_event_seat47(lv_event_t * e);
lv_obj_t * ui_seat47;
void ui_event_seat48(lv_event_t * e);
lv_obj_t * ui_seat48;
void ui_event_seat49(lv_event_t * e);
lv_obj_t * ui_seat49;
void ui_event_seat50(lv_event_t * e);
lv_obj_t * ui_seat50;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Label62;
lv_obj_t * ui_Label63;
lv_obj_t * ui_Label64;
lv_obj_t * ui_Label65;
void ui_event_buynumber(lv_event_t * e);
lv_obj_t * ui_buynumber;


// SCREEN: ui_dingdan
void ui_dingdan_screen_init(void);
lv_obj_t * ui_dingdan;
lv_obj_t * ui_dindanxinxi;
lv_obj_t * ui_Label85;
lv_obj_t * ui_Label80;
lv_obj_t * ui_Label82;
lv_obj_t * ui_Label83;
lv_obj_t * ui_orderlist1;
lv_obj_t * ui_template;
lv_obj_t * ui_rowticket;
lv_obj_t * ui_left;
lv_obj_t * ui_Labelmovie;
lv_obj_t * ui_Labelsession;
lv_obj_t * ui_Labelprice;
lv_obj_t * ui_divider;
lv_obj_t * ui_rowsnacks;
lv_obj_t * ui_Labeleattitle;
lv_obj_t * ui_Label86;


// SCREEN: ui_mediaplay
void ui_mediaplay_screen_init(void);
lv_obj_t * ui_mediaplay;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1045424809[3] = {&ui_img_145242593, &ui_img_873324722, &ui_img_208404457};
const lv_img_dsc_t * ui_imgset_371993653[4] = {&ui_img_663413319, &ui_img_663420742, &ui_img_663419717, &ui_img_663409996};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_start(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_guangao, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_guangao_screen_init);
    }
}
void ui_event_Image1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_guangao, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_guangao_screen_init);
    }
}
void ui_event_yes_or_no(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_start, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_start_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_start, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_start_screen_init);
    }
}
void ui_event_yes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        back(e);
    }
}
void ui_event_NO1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_login, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_login_screen_init);
    }
}
void ui_event_movie(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_yes_or_no, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yes_or_no_screen_init);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_update_balance();//进入"我的"页面前向云端查一次最新余额
        _ui_screen_change(&ui_mine, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mine_screen_init);
    }
}
void ui_event_Buttonyinyuan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_yinyuan, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yinyuan_screen_init);
    }
}
void ui_event_ImgButtonpig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_movie("小猪佩奇");//记录点击的电影名
        _ui_screen_change(&ui_yinyuan, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yinyuan_screen_init);
    }
}
void ui_event_ImgButtoncow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_movie("牛来");
        _ui_screen_change(&ui_yinyuan, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yinyuan_screen_init);
    }
}
void ui_event_ImgButtondog(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_movie("汪汪队");
        _ui_screen_change(&ui_yinyuan, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yinyuan_screen_init);
    }
}
void ui_event_ImgButtonggbond(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_movie("GGBOND");
        _ui_screen_change(&ui_yinyuan, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yinyuan_screen_init);
    }
}
void ui_event_ImgButtonlong4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_movie("龙4");
        _ui_screen_change(&ui_yinyuan, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yinyuan_screen_init);
    }
}
void ui_event_ImgButtonlong3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_movie("龙3");
        _ui_screen_change(&ui_yinyuan, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yinyuan_screen_init);
    }
}
void ui_event_ImgButtonlong2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_movie("龙2");
        _ui_screen_change(&ui_yinyuan, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yinyuan_screen_init);
    }
}
void ui_event_ImgButtonlong1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_movie("龙1");
        _ui_screen_change(&ui_yinyuan, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yinyuan_screen_init);
    }
}
void ui_event_ImgButtonnaiman(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_movie("乃万");
        _ui_screen_change(&ui_yinyuan, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yinyuan_screen_init);
    }
}
void ui_event_ImgButtonlpl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_movie("LPL");
        _ui_screen_change(&ui_yinyuan, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yinyuan_screen_init);
    }
}
void ui_event_food(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        buyfood(e);
    }
}
void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        charge1cloud(e);
    }
}
void ui_event_jian1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        jianwoods(e);
    }
}
void ui_event_add1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        addwoods(e);
    }
}
void ui_event_jian3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        jianwoods(e);
    }
}
void ui_event_jian4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        jianwoods(e);
    }
}
void ui_event_jian5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        jianwoods(e);
    }
}
void ui_event_jian6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        jianwoods(e);
    }
}
void ui_event_jian2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        jianwoods(e);
    }
}
void ui_event_add3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        addwoods(e);
    }
}
void ui_event_add4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        addwoods(e);
    }
}
void ui_event_add5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        addwoods(e);
    }
}
void ui_event_add6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        addwoods(e);
    }
}
void ui_event_add2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        addwoods(e);
    }
}


void ui_event_login(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_yes_or_no, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yes_or_no_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_yes_or_no, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yes_or_no_screen_init);
    }
}
void ui_event_username1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_username1);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_passname(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_passname);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        login_login(e);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_regis, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_regis_screen_init);
    }
}
void ui_event_regis(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_login, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_login_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_login, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_login_screen_init);
    }
}
void ui_event_username2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard2,  ui_username2);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_passname1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard2,  ui_passname1);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        regisandlogin(e);
    }
}
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_yes_or_no, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_yes_or_no_screen_init);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_movie, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_movie_screen_init);
    }
}
void ui_event_piao(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        searchdingdan(e);
    }
}

void ui_event_return(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        break1(e);
    }
}
void ui_event_return2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_movie, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_movie_screen_init);
    }
}
void ui_event_yinyuan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_movie, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_movie_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_movie, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_movie_screen_init);
    }
}
void ui_event_ImgButton12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_cinema(26);
        _ui_screen_change(&ui_selectseat, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_selectseat_screen_init);
    }
}
void ui_event_ImgButton13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_cinema(23);
        _ui_screen_change(&ui_selectseat, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_selectseat_screen_init);
    }
}
void ui_event_ImgButton14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_select_cinema(28);
        _ui_screen_change(&ui_selectseat, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_selectseat_screen_init);
    }
}
void ui_event_seat11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat11, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat13, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat14, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat15, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat16, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat17, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat18, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat19, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat20, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat12, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_confirm_tickets();//记录所选座位和票款，结账时和小吃合并
        _ui_screen_change(&ui_food, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_food_screen_init);
    }
}
void ui_event_seat10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat10, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat2, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat3, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat4, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat5, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat6, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat7, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat8, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat9, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat30, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat21, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat22, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat23, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat24, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat25, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat26, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat27(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat27, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat28, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat29(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat29, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat31, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat32, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat33, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat34(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat34, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat35(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat35, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat36(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat36, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat37(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat37, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat38(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat38, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat39(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat39, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat40(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat40, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat41(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat41, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat42(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat42, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat43(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat43, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat44(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat44, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat45(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat45, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat46(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat46, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat47(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat47, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat48(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat48, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat49(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat49, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_seat50(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_seat50, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_buynumber(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choosenumber(e);
    }
}
//手势返回：在屏幕上滑动即返回电影主页
static void gesture_back_movie(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) 
    {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_movie, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_movie_screen_init);
    }
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_failed_screen_init();
    ui_start_screen_init();
    ui_yes_or_no_screen_init();
    ui_movie_screen_init();
    ui_food_screen_init();
    ui_login_screen_init();
    ui_regis_screen_init();
    ui_guangao_screen_init();
    ui_success_screen_init();
    ui_mine_screen_init();
    ui_yinyuan_screen_init();
    ui_selectseat_screen_init();
    ui_dingdan_screen_init();

    ui____initial_actions0 = lv_obj_create(NULL);
    
    lv_obj_add_event_cb(ui_food,       gesture_back_movie, LV_EVENT_GESTURE, NULL);
    lv_obj_add_event_cb(ui_selectseat, gesture_back_movie, LV_EVENT_GESTURE, NULL);

    lv_obj_add_event_cb(ui_dingdan,    gesture_back_movie, LV_EVENT_GESTURE, NULL);
    lv_obj_add_event_cb(ui_orderlist1, gesture_back_movie, LV_EVENT_GESTURE, NULL);

    lv_obj_add_event_cb(ui_success,    gesture_back_movie, LV_EVENT_GESTURE, NULL);
    lv_obj_add_event_cb(ui_mine,       gesture_back_movie, LV_EVENT_GESTURE, NULL);

    lv_obj_add_event_cb(ui_failed,     gesture_back_movie, LV_EVENT_GESTURE, NULL);//支付/登录失败页：滑动返回电影页
    
    lv_disp_load_scr(ui_start);
}
