// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: yingyuan

#ifndef _YINGYUAN_UI_H
#define _YINGYUAN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#define _GNU_SOURCE

// #define  _POSIX_C_SOURCE

#include <strings.h>

#include <sys/types.h>
#include <sys/wait.h>

#include <sys/ipc.h>
#include <sys/msg.h>
#include <sys/shm.h>
#include <sys/sem.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <sys/select.h>
#include <sys/epoll.h>

#include <signal.h>
#include <pthread.h>
#include <errno.h>
#include <semaphore.h>
#include <time.h>

#include <netdb.h>
#include <netinet/in.h>
#include <netinet/ip.h> /* superset of previous */
#include <arpa/inet.h>  //本地转网络  网络转本地 头文件

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

#include "list.h"


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <errno.h>

#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>

#include "time1.h"

// SCREEN: ui_start
void ui_start_screen_init(void);
void ui_event_start(lv_event_t * e);
extern lv_obj_t * ui_start;
void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Label45;
// SCREEN: ui_yes_or_no
void ui_yes_or_no_screen_init(void);
void ui_event_yes_or_no(lv_event_t * e);
extern lv_obj_t * ui_yes_or_no;
void ui_event_yes(lv_event_t * e);
extern lv_obj_t * ui_yes;
extern lv_obj_t * ui_Label2;
void ui_event_NO1(lv_event_t * e);
extern lv_obj_t * ui_NO1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Label36;

LV_IMG_DECLARE(ui_img_failed_png); 
void ui_failed_screen_init(void);
extern lv_obj_t * ui_failed;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label16;

void date1(lv_obj_t *label);
void clock1(lv_obj_t *label);
void week1(lv_obj_t *label);

//已售座位：进选座页时统一置灰并禁止选中；支付成功后把座位记录为已售
void ui_apply_sold_seats(void);
void ui_mark_seat_desc_sold(const char *seat_desc);
//账号云备份：注册后上传服务器；开机/登录失败时从服务器拉取其他板子注册过的账号
void sync_account_to_server(const char *username, const char *password);
int fetch_server_accounts(void);

// SCREEN: ui_movie
void ui_movie_screen_init(void);
void ui_event_movie(lv_event_t * e);
extern lv_obj_t * ui_movie;
extern lv_obj_t * ui_Panellan;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Labelcowmine;
void ui_event_Buttonyinyuan(lv_event_t * e);
extern lv_obj_t * ui_Buttonyinyuan;
extern lv_obj_t * ui_Labelyinyuan_;
extern lv_obj_t * ui_Buttonmovie;
extern lv_obj_t * ui_Labelmovie1;
extern lv_obj_t * ui_Panelmianban;
extern lv_obj_t * ui_Panelhotmovie;
void ui_event_ImgButtonpig(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonpig;
void ui_event_ImgButtoncow(lv_event_t * e);
extern lv_obj_t * ui_ImgButtoncow;
extern lv_obj_t * ui_Labelcow;
void ui_event_ImgButtondog(lv_event_t * e);
extern lv_obj_t * ui_ImgButtondog;
extern lv_obj_t * ui_Labeldog;
void ui_event_ImgButtonggbond(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonggbond;
extern lv_obj_t * ui_Labelggbond;
extern lv_obj_t * ui_Labelpig;
extern lv_obj_t * ui_Panellastmovie;
void ui_event_ImgButtonlong4(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonlong4;
void ui_event_ImgButtonlong3(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonlong3;
void ui_event_ImgButtonlong2(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonlong2;
void ui_event_ImgButtonlong1(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonlong1;
extern lv_obj_t * ui_Labellong1;
extern lv_obj_t * ui_Labellong2;
extern lv_obj_t * ui_Labellong3;
extern lv_obj_t * ui_Labellong4;
extern lv_obj_t * ui_hotmovie;
extern lv_obj_t * ui_latsmovie;
extern lv_obj_t * ui_Panelyanchu;
void ui_event_ImgButtonnaiman(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonnaiman;
void ui_event_ImgButtonlpl(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonlpl;
extern lv_obj_t * ui_Labellpl;
extern lv_obj_t * ui_Labelnaiwan;
extern lv_obj_t * ui_Labelyanchu;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Labeldate;
extern lv_obj_t * ui_Labelday;
extern lv_obj_t * ui_Labelweather;
extern lv_obj_t * ui_Labelminutie;
// SCREEN: ui_food
void ui_food_screen_init(void);
void ui_event_food(lv_event_t * e);
extern lv_obj_t * ui_food;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_total2;
extern lv_obj_t * ui_number2;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_ImgButton15;
extern lv_obj_t * ui_ImgButton16;
extern lv_obj_t * ui_ImgButton18;
extern lv_obj_t * ui_ImgButton17;
extern lv_obj_t * ui_ImgButton19;
extern lv_obj_t * ui_ImgButton20;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
void ui_event_jian1(lv_event_t * e);
extern lv_obj_t * ui_jian1;
void ui_event_add1(lv_event_t * e);
extern lv_obj_t * ui_add1;
void ui_event_jian3(lv_event_t * e);
extern lv_obj_t * ui_jian3;
void ui_event_jian4(lv_event_t * e);
extern lv_obj_t * ui_jian4;
void ui_event_jian5(lv_event_t * e);
extern lv_obj_t * ui_jian5;
void ui_event_jian6(lv_event_t * e);
extern lv_obj_t * ui_jian6;
void ui_event_jian2(lv_event_t * e);
extern lv_obj_t * ui_jian2;
void ui_event_add3(lv_event_t * e);
extern lv_obj_t * ui_add3;
void ui_event_add4(lv_event_t * e);
extern lv_obj_t * ui_add4;
void ui_event_add5(lv_event_t * e);
extern lv_obj_t * ui_add5;
void ui_event_add6(lv_event_t * e);
extern lv_obj_t * ui_add6;
void ui_event_add2(lv_event_t * e);
extern lv_obj_t * ui_add2;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label66;
extern lv_obj_t * ui_Label67;
extern lv_obj_t * ui_Label68;
extern lv_obj_t * ui_Label69;
// SCREEN: ui_login
void ui_login_screen_init(void);
void ui_event_login(lv_event_t * e);
extern lv_obj_t * ui_login;
void ui_event_username1(lv_event_t * e);
extern lv_obj_t * ui_username1;
void ui_event_passname(lv_event_t * e);
extern lv_obj_t * ui_passname;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_TextArea5;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label9;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Label49;
// SCREEN: ui_regis
void ui_regis_screen_init(void);
void ui_event_regis(lv_event_t * e);
extern lv_obj_t * ui_regis;
void ui_event_username2(lv_event_t * e);
extern lv_obj_t * ui_username2;
void ui_event_passname1(lv_event_t * e);
extern lv_obj_t * ui_passname1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_TextArea1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Label52;
extern lv_obj_t * ui_Label53;
// SCREEN: ui_guangao
void ui_guangao_screen_init(void);
extern lv_obj_t * ui_guangao;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
// SCREEN: ui_success
void ui_success_screen_init(void);
extern lv_obj_t * ui_success;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label70;
extern lv_obj_t * ui_Label71;
extern lv_obj_t * ui_Label72;
extern lv_obj_t * ui_Label73;
// SCREEN: ui_mine
void ui_mine_screen_init(void);
extern lv_obj_t * ui_mine;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Label74;
extern lv_obj_t * ui_Label75;
extern lv_obj_t * ui_Label76;
extern lv_obj_t * ui_Label77;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label40;
void ui_event_piao(lv_event_t * e);
extern lv_obj_t * ui_piao;
void ui_event_mplay(lv_event_t * e);
extern lv_obj_t * ui_mplay;
void ui_event_return(lv_event_t * e);
extern lv_obj_t * ui_return;
extern lv_obj_t * ui_Label78;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label79;
void ui_event_return2(lv_event_t * e);
extern lv_obj_t * ui_return2;
extern lv_obj_t * ui_Label81;
// SCREEN: ui_yinyuan
void ui_yinyuan_screen_init(void);
void ui_event_yinyuan(lv_event_t * e);
extern lv_obj_t * ui_yinyuan;
extern lv_obj_t * ui_Panel4;
void ui_event_ImgButton12(lv_event_t * e);
extern lv_obj_t * ui_ImgButton12;
void ui_event_ImgButton13(lv_event_t * e);
extern lv_obj_t * ui_ImgButton13;
void ui_event_ImgButton14(lv_event_t * e);
extern lv_obj_t * ui_ImgButton14;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label58;
extern lv_obj_t * ui_Label59;
extern lv_obj_t * ui_Label60;
extern lv_obj_t * ui_Label61;
// SCREEN: ui_selectseat
void ui_selectseat_screen_init(void);
extern lv_obj_t * ui_selectseat;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_moviename;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_hang2;
void ui_event_seat11(lv_event_t * e);
extern lv_obj_t * ui_seat11;
void ui_event_seat13(lv_event_t * e);
extern lv_obj_t * ui_seat13;
void ui_event_seat14(lv_event_t * e);
extern lv_obj_t * ui_seat14;
void ui_event_seat15(lv_event_t * e);
extern lv_obj_t * ui_seat15;
void ui_event_seat16(lv_event_t * e);
extern lv_obj_t * ui_seat16;
void ui_event_seat17(lv_event_t * e);
extern lv_obj_t * ui_seat17;
void ui_event_seat18(lv_event_t * e);
extern lv_obj_t * ui_seat18;
void ui_event_seat19(lv_event_t * e);
extern lv_obj_t * ui_seat19;
void ui_event_seat20(lv_event_t * e);
extern lv_obj_t * ui_seat20;
void ui_event_seat12(lv_event_t * e);
extern lv_obj_t * ui_seat12;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_total;
extern lv_obj_t * ui_number;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_hang1;
void ui_event_seat10(lv_event_t * e);
extern lv_obj_t * ui_seat10;
void ui_event_seat1(lv_event_t * e);
extern lv_obj_t * ui_seat1;
void ui_event_seat2(lv_event_t * e);
extern lv_obj_t * ui_seat2;
void ui_event_seat3(lv_event_t * e);
extern lv_obj_t * ui_seat3;
void ui_event_seat4(lv_event_t * e);
extern lv_obj_t * ui_seat4;
void ui_event_seat5(lv_event_t * e);
extern lv_obj_t * ui_seat5;
void ui_event_seat6(lv_event_t * e);
extern lv_obj_t * ui_seat6;
void ui_event_seat7(lv_event_t * e);
extern lv_obj_t * ui_seat7;
void ui_event_seat8(lv_event_t * e);
extern lv_obj_t * ui_seat8;
void ui_event_seat9(lv_event_t * e);
extern lv_obj_t * ui_seat9;
extern lv_obj_t * ui_hang3;
void ui_event_seat30(lv_event_t * e);
extern lv_obj_t * ui_seat30;
void ui_event_seat21(lv_event_t * e);
extern lv_obj_t * ui_seat21;
void ui_event_seat22(lv_event_t * e);
extern lv_obj_t * ui_seat22;
void ui_event_seat23(lv_event_t * e);
extern lv_obj_t * ui_seat23;
void ui_event_seat24(lv_event_t * e);
extern lv_obj_t * ui_seat24;
void ui_event_seat25(lv_event_t * e);
extern lv_obj_t * ui_seat25;
void ui_event_seat26(lv_event_t * e);
extern lv_obj_t * ui_seat26;
void ui_event_seat27(lv_event_t * e);
extern lv_obj_t * ui_seat27;
void ui_event_seat28(lv_event_t * e);
extern lv_obj_t * ui_seat28;
void ui_event_seat29(lv_event_t * e);
extern lv_obj_t * ui_seat29;
extern lv_obj_t * ui_hang4;
void ui_event_seat31(lv_event_t * e);
extern lv_obj_t * ui_seat31;
void ui_event_seat32(lv_event_t * e);
extern lv_obj_t * ui_seat32;
void ui_event_seat33(lv_event_t * e);
extern lv_obj_t * ui_seat33;
void ui_event_seat34(lv_event_t * e);
extern lv_obj_t * ui_seat34;
void ui_event_seat35(lv_event_t * e);
extern lv_obj_t * ui_seat35;
void ui_event_seat36(lv_event_t * e);
extern lv_obj_t * ui_seat36;
void ui_event_seat37(lv_event_t * e);
extern lv_obj_t * ui_seat37;
void ui_event_seat38(lv_event_t * e);
extern lv_obj_t * ui_seat38;
void ui_event_seat39(lv_event_t * e);
extern lv_obj_t * ui_seat39;
void ui_event_seat40(lv_event_t * e);
extern lv_obj_t * ui_seat40;
extern lv_obj_t * ui_hang5;
void ui_event_seat41(lv_event_t * e);
extern lv_obj_t * ui_seat41;
void ui_event_seat42(lv_event_t * e);
extern lv_obj_t * ui_seat42;
void ui_event_seat43(lv_event_t * e);
extern lv_obj_t * ui_seat43;
void ui_event_seat44(lv_event_t * e);
extern lv_obj_t * ui_seat44;
void ui_event_seat45(lv_event_t * e);
extern lv_obj_t * ui_seat45;
void ui_event_seat46(lv_event_t * e);
extern lv_obj_t * ui_seat46;
void ui_event_seat47(lv_event_t * e);
extern lv_obj_t * ui_seat47;
void ui_event_seat48(lv_event_t * e);
extern lv_obj_t * ui_seat48;
void ui_event_seat49(lv_event_t * e);
extern lv_obj_t * ui_seat49;
void ui_event_seat50(lv_event_t * e);
extern lv_obj_t * ui_seat50;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label62;
extern lv_obj_t * ui_Label63;
extern lv_obj_t * ui_Label64;
extern lv_obj_t * ui_Label65;
void ui_event_buynumber(lv_event_t * e);
extern lv_obj_t * ui_buynumber;
// SCREEN: ui_dingdan
void ui_dingdan_screen_init(void);
extern lv_obj_t * ui_dingdan;
extern lv_obj_t * ui_dindanxinxi;
extern lv_obj_t * ui_Label85;
extern lv_obj_t * ui_Label80;
extern lv_obj_t * ui_Label82;
extern lv_obj_t * ui_Label83;
extern lv_obj_t * ui_orderlist1;
extern lv_obj_t * ui_template;
extern lv_obj_t * ui_rowticket;
extern lv_obj_t * ui_left;
extern lv_obj_t * ui_Labelmovie;
extern lv_obj_t * ui_Labelsession;
extern lv_obj_t * ui_Labelprice;
extern lv_obj_t * ui_divider;
extern lv_obj_t * ui_rowsnacks;
extern lv_obj_t * ui_Labeleattitle;
extern lv_obj_t * ui_Label86;
// SCREEN: ui_mediaplay
void ui_mediaplay_screen_init(void);
extern lv_obj_t * ui_mediaplay;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_startui_png);    // assets/startui.png
LV_IMG_DECLARE(ui_img_1373481471);    // assets/嘿嘿.png
LV_IMG_DECLARE(ui_img_373844247);    // assets/飞起来.png
LV_IMG_DECLARE(ui_img_pepepig_png);    // assets/pepepig.png
LV_IMG_DECLARE(ui_img_841450715);    // assets/牛来.png
LV_IMG_DECLARE(ui_img_620000976);    // assets/汪汪队.png
LV_IMG_DECLARE(ui_img_ggbond_png);    // assets/GGBOND.png
LV_IMG_DECLARE(ui_img_663409996);    // assets/龙4.png
LV_IMG_DECLARE(ui_img_663419717);    // assets/龙3.png
LV_IMG_DECLARE(ui_img_663420742);    // assets/龙2.png
LV_IMG_DECLARE(ui_img_663413319);    // assets/龙1.png
LV_IMG_DECLARE(ui_img_280646667);    // assets/乃万.png
LV_IMG_DECLARE(ui_img_lpl_png);    // assets/lpl.png
LV_IMG_DECLARE(ui_img_ls_png);    // assets/ls.png
LV_IMG_DECLARE(ui_img_zxf_png);    // assets/zxf.png
LV_IMG_DECLARE(ui_img_mx_png);    // assets/mx.png
LV_IMG_DECLARE(ui_img_man_png);    // assets/man.png
LV_IMG_DECLARE(ui_img_1081085947);    // assets/薯条.png
LV_IMG_DECLARE(ui_img_kfc_png);    // assets/KFC.png
LV_IMG_DECLARE(ui_img_1482295748);    // assets/减.png
LV_IMG_DECLARE(ui_img_1735873665);    // assets/加.png
LV_IMG_DECLARE(ui_img_yyy_png);    // assets/yyy.png
LV_IMG_DECLARE(ui_img_623033322);    // assets/无标题.png
LV_IMG_DECLARE(ui_img_1698191276);    // assets/成功.png
LV_IMG_DECLARE(ui_img_697434260);    // assets/在线.png
LV_IMG_DECLARE(ui_img_1523300687);    // assets/电影票.png
LV_IMG_DECLARE(ui_img_1152922109);    // assets/本人.png
LV_IMG_DECLARE(ui_img_145242593);    // assets/影院1.png
LV_IMG_DECLARE(ui_img_208404457);    // assets/影院3.png
LV_IMG_DECLARE(ui_img_873324722);    // assets/影院2.png
LV_IMG_DECLARE(ui_img_player_png);    // assets/player.png



LV_FONT_DECLARE(ui_font_zt2);
LV_FONT_DECLARE(ui_font_zt3);
LV_FONT_DECLARE(ui_font_zti);
LV_FONT_DECLARE(ui_font_yyyy22);
LV_FONT_DECLARE(ui_font_zzzz30);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
