// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: yingyuan

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void back(lv_event_t * e);
void buyfood(lv_event_t * e);
void charge1cloud(lv_event_t * e);
void jianwoods(lv_event_t * e);
void addwoods(lv_event_t * e);
void login_login(lv_event_t * e);
void regisandlogin(lv_event_t * e);
void searchdingdan(lv_event_t * e);
void break1(lv_event_t * e);
void choosenumber(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
